#define ACTION_C

#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <gsl/gsl_rng.h>
#include <gsl/gsl_complex.h>
#include <gsl/gsl_vector_double.h>
#include "update.h"
#include "matop.h"
#include "fileop.h"
#include "math.h"
#include <gsl/gsl_randist.h>
#include <gsl/gsl_sort_vector.h>
#include <gsl/gsl_blas.h>
#include "global.h"
#include "macros.h"
#include "data.h"
#include "statistics.h"


double delta2(gsl_matrix_complex* dM, int uM)
{

    gsl_complex res = GSL_COMPLEX_ZERO;


    // CASE: s=1

    for(int i=0; i<nHL; i++)
    {
        // trace of the clifford part
        gsl_matrix_complex* m = gsl_matrix_complex_alloc(dimG, dimG);
        gsl_blas_zgemm(CblasNoTrans, CblasNoTrans, GSL_COMPLEX_ONE, gamma[uM], gamma[i], GSL_COMPLEX_ZERO, m);
        gsl_complex A = trace(m);
        A = gsl_complex_mul_real(A, 4.);
        
        gsl_matrix_complex_free(m);

        if(GSL_REAL(A) != 0 || GSL_IMAG(A) != 0)
        {
            gsl_complex B;
            gsl_complex C;
            B = gsl_complex_mul(trace(dM), trace(MAT[i]));

            gsl_matrix_complex* m1 = gsl_matrix_complex_alloc(dim, dim);
            gsl_blas_zgemm(CblasNoTrans, CblasNoTrans, GSL_COMPLEX_ONE, dM, MAT[i], GSL_COMPLEX_ZERO, m1);
            C = trace(m1);
            gsl_matrix_complex_free(m1);

            if(uM < nH && i < nH)
                C = gsl_complex_mul_real(C, (double)dim);
            
            else if(uM >= nH && i >= nH)
                C = gsl_complex_mul_real(C, (double)(-dim));

            B = gsl_complex_add(B, C);
            A = gsl_complex_mul(A, B);

            res = gsl_complex_add(res, A);
        }
    }


    // CASE: s=2

    gsl_matrix_complex* m2 = gsl_matrix_complex_alloc(dim, dim);
    gsl_blas_zgemm(CblasNoTrans, CblasNoTrans, GSL_COMPLEX_ONE, dM, dM, GSL_COMPLEX_ZERO, m2);
    gsl_complex A = trace(m2);
    A = gsl_complex_mul_real(A, (double)dim);
    gsl_matrix_complex_free(m2);
    gsl_complex B = trace(dM);
    B = gsl_complex_mul(B, B);
    if(uM < nH)
        A = gsl_complex_add(A, B);
    else
        A = gsl_complex_sub(A, B);
    A = gsl_complex_mul_real(A, 2.*dimG);

    res = gsl_complex_add(res, A);

    //printf("%.15lf %.15lf\n", GSL_REAL(res), GSL_IMAG(res));

    return GSL_REAL(res);
}

double delta2_auto(gsl_matrix_complex* dM, int uM)
{
    // THIS CODE IS GENERATED BY delta.py SCRIPT (in the script folder)

    gsl_complex res = GSL_COMPLEX_ZERO;

    // CASE: s=1

    int* i1 = malloc(1*sizeof(int));
    for(i1[0]=0; i1[0]<nHL; i1[0]++)
    {
        gsl_complex pfac0 = GSL_COMPLEX_ZERO;
        pfac0 = gsl_complex_add(pfac0, gsl_complex_mul_real(gamma_table[2][uM+nHL*(i1[0])], (double)dim*e[i1[0]]*e[uM]+dim+dim+dim*e[i1[0]]*e[uM]));
        if(GSL_REAL(pfac0) != 0. || GSL_IMAG(pfac0) != 0.)
        {
            gsl_matrix_complex** array0 = malloc(2*sizeof(gsl_matrix_complex*));
            array0[0] = MAT[i1[0]];
            array0[1] = dM;
            gsl_matrix_complex* temp_mat0 = gsl_matrix_complex_alloc(dim, dim);
            matrix_multiprod(array0, 2, temp_mat0);
            pfac0 = gsl_complex_mul(pfac0, trace(temp_mat0));
            free(array0);
            gsl_matrix_complex_free(temp_mat0);
            res = gsl_complex_add(pfac0, res);
        }
        gsl_complex pfac1 = GSL_COMPLEX_ZERO;
        pfac1 = gsl_complex_add(pfac1, gsl_complex_mul_real(gamma_table[2][uM+nHL*(i1[0])], (double)e[uM]+e[i1[0]]+e[i1[0]]+e[uM]));
        if(GSL_REAL(pfac1) != 0. || GSL_IMAG(pfac1) != 0.)
        {
            pfac1 = gsl_complex_mul(pfac1, trace(dM));
            pfac1 = gsl_complex_mul(pfac1, trace(MAT[i1[0]]));
            res = gsl_complex_add(pfac1, res);
        }
    }
    free(i1);



    // CASE: s=2

    gsl_complex pfac0 = GSL_COMPLEX_ZERO;
    pfac0 = gsl_complex_add(pfac0, gsl_complex_mul_real(gsl_complex_rect(dimG, 0.), (double)dim+dim));
    if(GSL_REAL(pfac0) != 0. || GSL_IMAG(pfac0) != 0.)
    {
        gsl_matrix_complex** array0 = malloc(2*sizeof(gsl_matrix_complex*));
        array0[0] = dM;
        array0[1] = dM;
        gsl_matrix_complex* temp_mat0 = gsl_matrix_complex_alloc(dim, dim);
        matrix_multiprod(array0, 2, temp_mat0);
        pfac0 = gsl_complex_mul(pfac0, trace(temp_mat0));
        free(array0);
        gsl_matrix_complex_free(temp_mat0);
        res = gsl_complex_add(pfac0, res);
    }
    gsl_complex pfac1 = GSL_COMPLEX_ZERO;
    pfac1 = gsl_complex_add(pfac1, gsl_complex_mul_real(gsl_complex_rect(dimG, 0.), (double)2*e[uM]));
    if(GSL_REAL(pfac1) != 0. || GSL_IMAG(pfac1) != 0.)
    {
        pfac1 = gsl_complex_mul(pfac1, trace(dM));
        pfac1 = gsl_complex_mul(pfac1, trace(dM));
        res = gsl_complex_add(pfac1, res);
    }



    return GSL_REAL(res);
}



//printf("%.20lf\n", GSL_IMAG(res));
double delta4(gsl_matrix_complex* dM, int uM)
{
    // THIS CODE IS GENERATED BY delta.py SCRIPT (in the script folder)

    gsl_complex res = GSL_COMPLEX_ZERO;

    // CASE: s=1

    int* i1 = malloc(3*sizeof(int));
    for(i1[0]=0; i1[0]<nHL; i1[0]++)
    {
        for(i1[1]=0; i1[1]<nHL; i1[1]++)
        {
            for(i1[2]=0; i1[2]<nHL; i1[2]++)
            {
                gsl_complex pfac0 = GSL_COMPLEX_ZERO;
                pfac0 = gsl_complex_add(pfac0, gsl_complex_mul_real(gamma_table[4][uM+nHL*(i1[2]+nHL*(i1[1]+nHL*(i1[0])))], (double)dim*e[i1[0]]*e[uM]*e[i1[2]]*e[i1[1]]+dim*e[i1[0]]*e[uM]*e[i1[2]]*e[i1[1]]));
                if(GSL_REAL(pfac0) != 0. || GSL_IMAG(pfac0) != 0.)
                {
                    gsl_matrix_complex** array0 = malloc(4*sizeof(gsl_matrix_complex*));
                    array0[0] = MAT[i1[0]];
                    array0[1] = dM;
                    array0[2] = MAT[i1[2]];
                    array0[3] = MAT[i1[1]];
                    gsl_matrix_complex* temp_mat0 = gsl_matrix_complex_alloc(dim, dim);
                    matrix_multiprod(array0, 4, temp_mat0);
                    pfac0 = gsl_complex_mul(pfac0, trace(temp_mat0));
                    free(array0);
                    gsl_matrix_complex_free(temp_mat0);
                    res = gsl_complex_add(pfac0, res);
                }
                gsl_complex pfac1 = GSL_COMPLEX_ZERO;
                pfac1 = gsl_complex_add(pfac1, gsl_complex_mul_real(gamma_table[4][i1[2]+nHL*(i1[1]+nHL*(uM+nHL*(i1[0])))], (double)e[i1[1]]*e[uM]*e[i1[2]]));
                pfac1 = gsl_complex_add(pfac1, gsl_complex_mul_real(gamma_table[4][i1[2]+nHL*(uM+nHL*(i1[1]+nHL*(i1[0])))], (double)e[i1[0]]));
                pfac1 = gsl_complex_add(pfac1, gsl_complex_mul_real(gamma_table[4][uM+nHL*(i1[2]+nHL*(i1[1]+nHL*(i1[0])))], (double)e[i1[1]]*e[uM]*e[i1[2]]+e[i1[1]]*e[uM]*e[i1[2]]));
                if(GSL_REAL(pfac1) != 0. || GSL_IMAG(pfac1) != 0.)
                {
                    gsl_matrix_complex** array0 = malloc(3*sizeof(gsl_matrix_complex*));
                    array0[0] = MAT[i1[1]];
                    array0[1] = dM;
                    array0[2] = MAT[i1[2]];
                    gsl_matrix_complex* temp_mat0 = gsl_matrix_complex_alloc(dim, dim);
                    matrix_multiprod(array0, 3, temp_mat0);
                    pfac1 = gsl_complex_mul(pfac1, trace(temp_mat0));
                    pfac1 = gsl_complex_mul(pfac1, trace(MAT[i1[0]]));
                    free(array0);
                    gsl_matrix_complex_free(temp_mat0);
                    res = gsl_complex_add(pfac1, res);
                }
                gsl_complex pfac2 = GSL_COMPLEX_ZERO;
                pfac2 = gsl_complex_add(pfac2, gsl_complex_mul_real(gamma_table[4][i1[2]+nHL*(i1[1]+nHL*(uM+nHL*(i1[0])))], (double)e[i1[1]]));
                pfac2 = gsl_complex_add(pfac2, gsl_complex_mul_real(gamma_table[4][i1[2]+nHL*(uM+nHL*(i1[1]+nHL*(i1[0])))], (double)e[i1[1]]));
                pfac2 = gsl_complex_add(pfac2, gsl_complex_mul_real(gamma_table[4][uM+nHL*(i1[2]+nHL*(i1[1]+nHL*(i1[0])))], (double)e[i1[0]]*e[uM]*e[i1[2]]+e[i1[0]]*e[uM]*e[i1[2]]));
                if(GSL_REAL(pfac2) != 0. || GSL_IMAG(pfac2) != 0.)
                {
                    gsl_matrix_complex** array1 = malloc(3*sizeof(gsl_matrix_complex*));
                    array1[0] = MAT[i1[0]];
                    array1[1] = dM;
                    array1[2] = MAT[i1[2]];
                    gsl_matrix_complex* temp_mat1 = gsl_matrix_complex_alloc(dim, dim);
                    matrix_multiprod(array1, 3, temp_mat1);
                    pfac2 = gsl_complex_mul(pfac2, trace(MAT[i1[1]]));
                    pfac2 = gsl_complex_mul(pfac2, trace(temp_mat1));
                    free(array1);
                    gsl_matrix_complex_free(temp_mat1);
                    res = gsl_complex_add(pfac2, res);
                }
                gsl_complex pfac3 = GSL_COMPLEX_ZERO;
                pfac3 = gsl_complex_add(pfac3, gsl_complex_mul_real(gamma_table[4][i1[2]+nHL*(i1[1]+nHL*(uM+nHL*(i1[0])))], (double)e[i1[2]]*e[uM]+e[i1[0]]*e[i1[1]]));
                pfac3 = gsl_complex_add(pfac3, gsl_complex_mul_real(gamma_table[4][i1[2]+nHL*(uM+nHL*(i1[1]+nHL*(i1[0])))], (double)e[i1[0]]*e[i1[1]]+e[i1[2]]*e[uM]));
                pfac3 = gsl_complex_add(pfac3, gsl_complex_mul_real(gamma_table[4][uM+nHL*(i1[2]+nHL*(i1[1]+nHL*(i1[0])))], (double)e[i1[2]]*e[uM]+e[i1[0]]*e[i1[1]]+e[i1[0]]*e[i1[1]]+e[i1[2]]*e[uM]));
                if(GSL_REAL(pfac3) != 0. || GSL_IMAG(pfac3) != 0.)
                {
                    gsl_matrix_complex** array0 = malloc(2*sizeof(gsl_matrix_complex*));
                    array0[0] = MAT[i1[2]];
                    array0[1] = dM;
                    gsl_matrix_complex* temp_mat0 = gsl_matrix_complex_alloc(dim, dim);
                    matrix_multiprod(array0, 2, temp_mat0);
                    gsl_matrix_complex** array1 = malloc(2*sizeof(gsl_matrix_complex*));
                    array1[0] = MAT[i1[0]];
                    array1[1] = MAT[i1[1]];
                    gsl_matrix_complex* temp_mat1 = gsl_matrix_complex_alloc(dim, dim);
                    matrix_multiprod(array1, 2, temp_mat1);
                    pfac3 = gsl_complex_mul(pfac3, trace(temp_mat0));
                    pfac3 = gsl_complex_mul(pfac3, trace(temp_mat1));
                    free(array0);
                    free(array1);
                    gsl_matrix_complex_free(temp_mat0);
                    gsl_matrix_complex_free(temp_mat1);
                    res = gsl_complex_add(pfac3, res);
                }
                gsl_complex pfac4 = GSL_COMPLEX_ZERO;
                pfac4 = gsl_complex_add(pfac4, gsl_complex_mul_real(gamma_table[4][i1[2]+nHL*(i1[1]+nHL*(uM+nHL*(i1[0])))], (double)e[i1[2]]));
                pfac4 = gsl_complex_add(pfac4, gsl_complex_mul_real(gamma_table[4][i1[2]+nHL*(uM+nHL*(i1[1]+nHL*(i1[0])))], (double)e[i1[0]]*e[uM]*e[i1[1]]));
                pfac4 = gsl_complex_add(pfac4, gsl_complex_mul_real(gamma_table[4][uM+nHL*(i1[2]+nHL*(i1[1]+nHL*(i1[0])))], (double)e[i1[0]]*e[uM]*e[i1[1]]+e[i1[0]]*e[uM]*e[i1[1]]));
                if(GSL_REAL(pfac4) != 0. || GSL_IMAG(pfac4) != 0.)
                {
                    gsl_matrix_complex** array1 = malloc(3*sizeof(gsl_matrix_complex*));
                    array1[0] = MAT[i1[0]];
                    array1[1] = dM;
                    array1[2] = MAT[i1[1]];
                    gsl_matrix_complex* temp_mat1 = gsl_matrix_complex_alloc(dim, dim);
                    matrix_multiprod(array1, 3, temp_mat1);
                    pfac4 = gsl_complex_mul(pfac4, trace(MAT[i1[2]]));
                    pfac4 = gsl_complex_mul(pfac4, trace(temp_mat1));
                    free(array1);
                    gsl_matrix_complex_free(temp_mat1);
                    res = gsl_complex_add(pfac4, res);
                }
                gsl_complex pfac5 = GSL_COMPLEX_ZERO;
                pfac5 = gsl_complex_add(pfac5, gsl_complex_mul_real(gamma_table[4][i1[2]+nHL*(i1[1]+nHL*(uM+nHL*(i1[0])))], (double)e[i1[1]]*e[uM]+e[i1[0]]*e[i1[2]]));
                pfac5 = gsl_complex_add(pfac5, gsl_complex_mul_real(gamma_table[4][i1[2]+nHL*(uM+nHL*(i1[1]+nHL*(i1[0])))], (double)e[i1[0]]*e[i1[2]]+e[i1[1]]*e[uM]));
                pfac5 = gsl_complex_add(pfac5, gsl_complex_mul_real(gamma_table[4][uM+nHL*(i1[2]+nHL*(i1[1]+nHL*(i1[0])))], (double)e[i1[1]]*e[uM]+e[i1[0]]*e[i1[2]]+e[i1[0]]*e[i1[2]]+e[i1[1]]*e[uM]));
                if(GSL_REAL(pfac5) != 0. || GSL_IMAG(pfac5) != 0.)
                {
                    gsl_matrix_complex** array0 = malloc(2*sizeof(gsl_matrix_complex*));
                    array0[0] = MAT[i1[1]];
                    array0[1] = dM;
                    gsl_matrix_complex* temp_mat0 = gsl_matrix_complex_alloc(dim, dim);
                    matrix_multiprod(array0, 2, temp_mat0);
                    gsl_matrix_complex** array1 = malloc(2*sizeof(gsl_matrix_complex*));
                    array1[0] = MAT[i1[0]];
                    array1[1] = MAT[i1[2]];
                    gsl_matrix_complex* temp_mat1 = gsl_matrix_complex_alloc(dim, dim);
                    matrix_multiprod(array1, 2, temp_mat1);
                    pfac5 = gsl_complex_mul(pfac5, trace(temp_mat0));
                    pfac5 = gsl_complex_mul(pfac5, trace(temp_mat1));
                    free(array0);
                    free(array1);
                    gsl_matrix_complex_free(temp_mat0);
                    gsl_matrix_complex_free(temp_mat1);
                    res = gsl_complex_add(pfac5, res);
                }
                gsl_complex pfac6 = GSL_COMPLEX_ZERO;
                pfac6 = gsl_complex_add(pfac6, gsl_complex_mul_real(gamma_table[4][i1[2]+nHL*(i1[1]+nHL*(uM+nHL*(i1[0])))], (double)e[i1[0]]*e[uM]+e[i1[1]]*e[i1[2]]));
                pfac6 = gsl_complex_add(pfac6, gsl_complex_mul_real(gamma_table[4][i1[2]+nHL*(uM+nHL*(i1[1]+nHL*(i1[0])))], (double)e[i1[1]]*e[i1[2]]+e[i1[0]]*e[uM]));
                pfac6 = gsl_complex_add(pfac6, gsl_complex_mul_real(gamma_table[4][uM+nHL*(i1[2]+nHL*(i1[1]+nHL*(i1[0])))], (double)e[i1[0]]*e[uM]+e[i1[1]]*e[i1[2]]+e[i1[1]]*e[i1[2]]+e[i1[0]]*e[uM]));
                if(GSL_REAL(pfac6) != 0. || GSL_IMAG(pfac6) != 0.)
                {
                    gsl_matrix_complex** array0 = malloc(2*sizeof(gsl_matrix_complex*));
                    array0[0] = MAT[i1[1]];
                    array0[1] = MAT[i1[2]];
                    gsl_matrix_complex* temp_mat0 = gsl_matrix_complex_alloc(dim, dim);
                    matrix_multiprod(array0, 2, temp_mat0);
                    gsl_matrix_complex** array1 = malloc(2*sizeof(gsl_matrix_complex*));
                    array1[0] = MAT[i1[0]];
                    array1[1] = dM;
                    gsl_matrix_complex* temp_mat1 = gsl_matrix_complex_alloc(dim, dim);
                    matrix_multiprod(array1, 2, temp_mat1);
                    pfac6 = gsl_complex_mul(pfac6, trace(temp_mat0));
                    pfac6 = gsl_complex_mul(pfac6, trace(temp_mat1));
                    free(array0);
                    free(array1);
                    gsl_matrix_complex_free(temp_mat0);
                    gsl_matrix_complex_free(temp_mat1);
                    res = gsl_complex_add(pfac6, res);
                }
                gsl_complex pfac7 = GSL_COMPLEX_ZERO;
                pfac7 = gsl_complex_add(pfac7, gsl_complex_mul_real(gamma_table[4][i1[2]+nHL*(i1[1]+nHL*(uM+nHL*(i1[0])))], (double)e[uM]));
                pfac7 = gsl_complex_add(pfac7, gsl_complex_mul_real(gamma_table[4][i1[2]+nHL*(uM+nHL*(i1[1]+nHL*(i1[0])))], (double)e[uM]));
                pfac7 = gsl_complex_add(pfac7, gsl_complex_mul_real(gamma_table[4][uM+nHL*(i1[2]+nHL*(i1[1]+nHL*(i1[0])))], (double)e[uM]+e[uM]));
                if(GSL_REAL(pfac7) != 0. || GSL_IMAG(pfac7) != 0.)
                {
                    gsl_matrix_complex** array1 = malloc(3*sizeof(gsl_matrix_complex*));
                    array1[0] = MAT[i1[0]];
                    array1[1] = MAT[i1[1]];
                    array1[2] = MAT[i1[2]];
                    gsl_matrix_complex* temp_mat1 = gsl_matrix_complex_alloc(dim, dim);
                    matrix_multiprod(array1, 3, temp_mat1);
                    pfac7 = gsl_complex_mul(pfac7, trace(dM));
                    pfac7 = gsl_complex_mul(pfac7, trace(temp_mat1));
                    free(array1);
                    gsl_matrix_complex_free(temp_mat1);
                    res = gsl_complex_add(pfac7, res);
                }
                gsl_complex pfac8 = GSL_COMPLEX_ZERO;
                pfac8 = gsl_complex_add(pfac8, gsl_complex_mul_real(gamma_table[4][i1[2]+nHL*(i1[1]+nHL*(uM+nHL*(i1[0])))], (double)e[i1[0]]*e[i1[2]]*e[i1[1]]));
                pfac8 = gsl_complex_add(pfac8, gsl_complex_mul_real(gamma_table[4][i1[2]+nHL*(uM+nHL*(i1[1]+nHL*(i1[0])))], (double)e[i1[0]]*e[i1[2]]*e[i1[1]]));
                pfac8 = gsl_complex_add(pfac8, gsl_complex_mul_real(gamma_table[4][uM+nHL*(i1[2]+nHL*(i1[1]+nHL*(i1[0])))], (double)e[i1[0]]*e[i1[2]]*e[i1[1]]+e[i1[0]]*e[i1[2]]*e[i1[1]]));
                if(GSL_REAL(pfac8) != 0. || GSL_IMAG(pfac8) != 0.)
                {
                    gsl_matrix_complex** array1 = malloc(3*sizeof(gsl_matrix_complex*));
                    array1[0] = MAT[i1[0]];
                    array1[1] = MAT[i1[2]];
                    array1[2] = MAT[i1[1]];
                    gsl_matrix_complex* temp_mat1 = gsl_matrix_complex_alloc(dim, dim);
                    matrix_multiprod(array1, 3, temp_mat1);
                    pfac8 = gsl_complex_mul(pfac8, trace(dM));
                    pfac8 = gsl_complex_mul(pfac8, trace(temp_mat1));
                    free(array1);
                    gsl_matrix_complex_free(temp_mat1);
                    res = gsl_complex_add(pfac8, res);
                }
                gsl_complex pfac9 = GSL_COMPLEX_ZERO;
                pfac9 = gsl_complex_add(pfac9, gsl_complex_mul_real(gamma_table[4][i1[2]+nHL*(i1[1]+nHL*(uM+nHL*(i1[0])))], (double)e[i1[0]]*e[i1[1]]*e[uM]));
                pfac9 = gsl_complex_add(pfac9, gsl_complex_mul_real(gamma_table[4][i1[2]+nHL*(uM+nHL*(i1[1]+nHL*(i1[0])))], (double)e[i1[2]]));
                pfac9 = gsl_complex_add(pfac9, gsl_complex_mul_real(gamma_table[4][uM+nHL*(i1[2]+nHL*(i1[1]+nHL*(i1[0])))], (double)e[i1[2]]+e[i1[2]]));
                if(GSL_REAL(pfac9) != 0. || GSL_IMAG(pfac9) != 0.)
                {
                    gsl_matrix_complex** array1 = malloc(3*sizeof(gsl_matrix_complex*));
                    array1[0] = MAT[i1[0]];
                    array1[1] = MAT[i1[1]];
                    array1[2] = dM;
                    gsl_matrix_complex* temp_mat1 = gsl_matrix_complex_alloc(dim, dim);
                    matrix_multiprod(array1, 3, temp_mat1);
                    pfac9 = gsl_complex_mul(pfac9, trace(MAT[i1[2]]));
                    pfac9 = gsl_complex_mul(pfac9, trace(temp_mat1));
                    free(array1);
                    gsl_matrix_complex_free(temp_mat1);
                    res = gsl_complex_add(pfac9, res);
                }
                gsl_complex pfac10 = GSL_COMPLEX_ZERO;
                pfac10 = gsl_complex_add(pfac10, gsl_complex_mul_real(gamma_table[4][i1[2]+nHL*(i1[1]+nHL*(uM+nHL*(i1[0])))], (double)e[i1[0]]*e[i1[2]]*e[uM]));
                pfac10 = gsl_complex_add(pfac10, gsl_complex_mul_real(gamma_table[4][i1[2]+nHL*(uM+nHL*(i1[1]+nHL*(i1[0])))], (double)e[i1[0]]*e[i1[2]]*e[uM]));
                pfac10 = gsl_complex_add(pfac10, gsl_complex_mul_real(gamma_table[4][uM+nHL*(i1[2]+nHL*(i1[1]+nHL*(i1[0])))], (double)e[i1[1]]+e[i1[1]]));
                if(GSL_REAL(pfac10) != 0. || GSL_IMAG(pfac10) != 0.)
                {
                    gsl_matrix_complex** array1 = malloc(3*sizeof(gsl_matrix_complex*));
                    array1[0] = MAT[i1[0]];
                    array1[1] = MAT[i1[2]];
                    array1[2] = dM;
                    gsl_matrix_complex* temp_mat1 = gsl_matrix_complex_alloc(dim, dim);
                    matrix_multiprod(array1, 3, temp_mat1);
                    pfac10 = gsl_complex_mul(pfac10, trace(MAT[i1[1]]));
                    pfac10 = gsl_complex_mul(pfac10, trace(temp_mat1));
                    free(array1);
                    gsl_matrix_complex_free(temp_mat1);
                    res = gsl_complex_add(pfac10, res);
                }
                gsl_complex pfac11 = GSL_COMPLEX_ZERO;
                pfac11 = gsl_complex_add(pfac11, gsl_complex_mul_real(gamma_table[4][i1[2]+nHL*(i1[1]+nHL*(uM+nHL*(i1[0])))], (double)e[i1[0]]));
                pfac11 = gsl_complex_add(pfac11, gsl_complex_mul_real(gamma_table[4][i1[2]+nHL*(uM+nHL*(i1[1]+nHL*(i1[0])))], (double)e[i1[1]]*e[i1[2]]*e[uM]));
                pfac11 = gsl_complex_add(pfac11, gsl_complex_mul_real(gamma_table[4][uM+nHL*(i1[2]+nHL*(i1[1]+nHL*(i1[0])))], (double)e[i1[0]]+e[i1[0]]));
                if(GSL_REAL(pfac11) != 0. || GSL_IMAG(pfac11) != 0.)
                {
                    gsl_matrix_complex** array0 = malloc(3*sizeof(gsl_matrix_complex*));
                    array0[0] = MAT[i1[1]];
                    array0[1] = MAT[i1[2]];
                    array0[2] = dM;
                    gsl_matrix_complex* temp_mat0 = gsl_matrix_complex_alloc(dim, dim);
                    matrix_multiprod(array0, 3, temp_mat0);
                    pfac11 = gsl_complex_mul(pfac11, trace(temp_mat0));
                    pfac11 = gsl_complex_mul(pfac11, trace(MAT[i1[0]]));
                    free(array0);
                    gsl_matrix_complex_free(temp_mat0);
                    res = gsl_complex_add(pfac11, res);
                }
                gsl_complex pfac12 = GSL_COMPLEX_ZERO;
                pfac12 = gsl_complex_add(pfac12, gsl_complex_mul_real(gamma_table[4][uM+nHL*(i1[2]+nHL*(i1[1]+nHL*(i1[0])))], (double)dim+dim));
                if(GSL_REAL(pfac12) != 0. || GSL_IMAG(pfac12) != 0.)
                {
                    gsl_matrix_complex** array0 = malloc(4*sizeof(gsl_matrix_complex*));
                    array0[0] = MAT[i1[0]];
                    array0[1] = MAT[i1[1]];
                    array0[2] = MAT[i1[2]];
                    array0[3] = dM;
                    gsl_matrix_complex* temp_mat0 = gsl_matrix_complex_alloc(dim, dim);
                    matrix_multiprod(array0, 4, temp_mat0);
                    pfac12 = gsl_complex_mul(pfac12, trace(temp_mat0));
                    free(array0);
                    gsl_matrix_complex_free(temp_mat0);
                    res = gsl_complex_add(pfac12, res);
                }
                gsl_complex pfac13 = GSL_COMPLEX_ZERO;
                pfac13 = gsl_complex_add(pfac13, gsl_complex_mul_real(gamma_table[4][i1[2]+nHL*(i1[1]+nHL*(uM+nHL*(i1[0])))], (double)dim*e[i1[0]]*e[i1[2]]*e[i1[1]]*e[uM]));
                if(GSL_REAL(pfac13) != 0. || GSL_IMAG(pfac13) != 0.)
                {
                    gsl_matrix_complex** array0 = malloc(4*sizeof(gsl_matrix_complex*));
                    array0[0] = MAT[i1[0]];
                    array0[1] = MAT[i1[2]];
                    array0[2] = MAT[i1[1]];
                    array0[3] = dM;
                    gsl_matrix_complex* temp_mat0 = gsl_matrix_complex_alloc(dim, dim);
                    matrix_multiprod(array0, 4, temp_mat0);
                    pfac13 = gsl_complex_mul(pfac13, trace(temp_mat0));
                    free(array0);
                    gsl_matrix_complex_free(temp_mat0);
                    res = gsl_complex_add(pfac13, res);
                }
                gsl_complex pfac14 = GSL_COMPLEX_ZERO;
                pfac14 = gsl_complex_add(pfac14, gsl_complex_mul_real(gamma_table[4][i1[2]+nHL*(i1[1]+nHL*(uM+nHL*(i1[0])))], (double)dim));
                if(GSL_REAL(pfac14) != 0. || GSL_IMAG(pfac14) != 0.)
                {
                    gsl_matrix_complex** array0 = malloc(4*sizeof(gsl_matrix_complex*));
                    array0[0] = MAT[i1[0]];
                    array0[1] = dM;
                    array0[2] = MAT[i1[1]];
                    array0[3] = MAT[i1[2]];
                    gsl_matrix_complex* temp_mat0 = gsl_matrix_complex_alloc(dim, dim);
                    matrix_multiprod(array0, 4, temp_mat0);
                    pfac14 = gsl_complex_mul(pfac14, trace(temp_mat0));
                    free(array0);
                    gsl_matrix_complex_free(temp_mat0);
                    res = gsl_complex_add(pfac14, res);
                }
                gsl_complex pfac15 = GSL_COMPLEX_ZERO;
                pfac15 = gsl_complex_add(pfac15, gsl_complex_mul_real(gamma_table[4][i1[2]+nHL*(uM+nHL*(i1[1]+nHL*(i1[0])))], (double)dim*e[i1[0]]*e[i1[2]]*e[uM]*e[i1[1]]));
                if(GSL_REAL(pfac15) != 0. || GSL_IMAG(pfac15) != 0.)
                {
                    gsl_matrix_complex** array0 = malloc(4*sizeof(gsl_matrix_complex*));
                    array0[0] = MAT[i1[0]];
                    array0[1] = MAT[i1[2]];
                    array0[2] = dM;
                    array0[3] = MAT[i1[1]];
                    gsl_matrix_complex* temp_mat0 = gsl_matrix_complex_alloc(dim, dim);
                    matrix_multiprod(array0, 4, temp_mat0);
                    pfac15 = gsl_complex_mul(pfac15, trace(temp_mat0));
                    free(array0);
                    gsl_matrix_complex_free(temp_mat0);
                    res = gsl_complex_add(pfac15, res);
                }
                gsl_complex pfac16 = GSL_COMPLEX_ZERO;
                pfac16 = gsl_complex_add(pfac16, gsl_complex_mul_real(gamma_table[4][i1[2]+nHL*(uM+nHL*(i1[1]+nHL*(i1[0])))], (double)dim));
                if(GSL_REAL(pfac16) != 0. || GSL_IMAG(pfac16) != 0.)
                {
                    gsl_matrix_complex** array0 = malloc(4*sizeof(gsl_matrix_complex*));
                    array0[0] = MAT[i1[0]];
                    array0[1] = MAT[i1[1]];
                    array0[2] = dM;
                    array0[3] = MAT[i1[2]];
                    gsl_matrix_complex* temp_mat0 = gsl_matrix_complex_alloc(dim, dim);
                    matrix_multiprod(array0, 4, temp_mat0);
                    pfac16 = gsl_complex_mul(pfac16, trace(temp_mat0));
                    free(array0);
                    gsl_matrix_complex_free(temp_mat0);
                    res = gsl_complex_add(pfac16, res);
                }
            }
        }
    }
    free(i1);



    // CASE: s=2

    int* i2 = malloc(2*sizeof(int));
    for(i2[0]=0; i2[0]<nHL; i2[0]++)
    {
        for(i2[1]=0; i2[1]<nHL; i2[1]++)
        {
            gsl_complex pfac0 = GSL_COMPLEX_ZERO;
            pfac0 = gsl_complex_add(pfac0, gsl_complex_mul_real(gamma_table[2][i2[1]+nHL*(i2[0])], (double)dim*e[i2[0]]*e[i2[1]]+dim+dim*e[i2[0]]*e[i2[1]]+dim*e[i2[0]]*e[i2[1]]));
            if(GSL_REAL(pfac0) != 0. || GSL_IMAG(pfac0) != 0.)
            {
                gsl_matrix_complex** array0 = malloc(4*sizeof(gsl_matrix_complex*));
                array0[0] = MAT[i2[0]];
                array0[1] = dM;
                array0[2] = dM;
                array0[3] = MAT[i2[1]];
                gsl_matrix_complex* temp_mat0 = gsl_matrix_complex_alloc(dim, dim);
                matrix_multiprod(array0, 4, temp_mat0);
                pfac0 = gsl_complex_mul(pfac0, trace(temp_mat0));
                free(array0);
                gsl_matrix_complex_free(temp_mat0);
                res = gsl_complex_add(pfac0, res);
            }
            gsl_complex pfac1 = GSL_COMPLEX_ZERO;
            pfac1 = gsl_complex_add(pfac1, gsl_complex_mul_real(gamma_table[2][i2[1]+nHL*(i2[0])], (double)e[i2[1]]+e[i2[0]]+e[i2[1]]+e[i2[0]]+e[i2[0]]+e[i2[1]]));
            pfac1 = gsl_complex_add(pfac1, gsl_complex_mul_real(gamma_table[4][uM+nHL*(i2[1]+nHL*(uM+nHL*(i2[0])))], (double)e[i2[0]]+e[i2[1]]));
            if(GSL_REAL(pfac1) != 0. || GSL_IMAG(pfac1) != 0.)
            {
                gsl_matrix_complex** array0 = malloc(3*sizeof(gsl_matrix_complex*));
                array0[0] = MAT[i2[1]];
                array0[1] = dM;
                array0[2] = dM;
                gsl_matrix_complex* temp_mat0 = gsl_matrix_complex_alloc(dim, dim);
                matrix_multiprod(array0, 3, temp_mat0);
                pfac1 = gsl_complex_mul(pfac1, trace(temp_mat0));
                pfac1 = gsl_complex_mul(pfac1, trace(MAT[i2[0]]));
                free(array0);
                gsl_matrix_complex_free(temp_mat0);
                res = gsl_complex_add(pfac1, res);
            }
            gsl_complex pfac2 = GSL_COMPLEX_ZERO;
            pfac2 = gsl_complex_add(pfac2, gsl_complex_mul_real(gamma_table[2][i2[1]+nHL*(i2[0])], (double)e[i2[0]]+e[i2[1]]+e[i2[0]]+e[i2[1]]+e[i2[1]]+e[i2[0]]));
            pfac2 = gsl_complex_add(pfac2, gsl_complex_mul_real(gamma_table[4][uM+nHL*(i2[1]+nHL*(uM+nHL*(i2[0])))], (double)e[i2[1]]+e[i2[0]]));
            if(GSL_REAL(pfac2) != 0. || GSL_IMAG(pfac2) != 0.)
            {
                gsl_matrix_complex** array1 = malloc(3*sizeof(gsl_matrix_complex*));
                array1[0] = MAT[i2[0]];
                array1[1] = dM;
                array1[2] = dM;
                gsl_matrix_complex* temp_mat1 = gsl_matrix_complex_alloc(dim, dim);
                matrix_multiprod(array1, 3, temp_mat1);
                pfac2 = gsl_complex_mul(pfac2, trace(MAT[i2[1]]));
                pfac2 = gsl_complex_mul(pfac2, trace(temp_mat1));
                free(array1);
                gsl_matrix_complex_free(temp_mat1);
                res = gsl_complex_add(pfac2, res);
            }
            gsl_complex pfac3 = GSL_COMPLEX_ZERO;
            pfac3 = gsl_complex_add(pfac3, gsl_complex_mul_real(gamma_table[2][i2[1]+nHL*(i2[0])], (double)1+e[i2[0]]*e[i2[1]]+1+e[i2[0]]*e[i2[1]]+e[i2[0]]*e[i2[1]]+1));
            pfac3 = gsl_complex_add(pfac3, gsl_complex_mul_real(gamma_table[4][uM+nHL*(i2[1]+nHL*(uM+nHL*(i2[0])))], (double)e[i2[0]]*e[i2[1]]+1));
            if(GSL_REAL(pfac3) != 0. || GSL_IMAG(pfac3) != 0.)
            {
                gsl_matrix_complex** array0 = malloc(2*sizeof(gsl_matrix_complex*));
                array0[0] = dM;
                array0[1] = dM;
                gsl_matrix_complex* temp_mat0 = gsl_matrix_complex_alloc(dim, dim);
                matrix_multiprod(array0, 2, temp_mat0);
                gsl_matrix_complex** array1 = malloc(2*sizeof(gsl_matrix_complex*));
                array1[0] = MAT[i2[0]];
                array1[1] = MAT[i2[1]];
                gsl_matrix_complex* temp_mat1 = gsl_matrix_complex_alloc(dim, dim);
                matrix_multiprod(array1, 2, temp_mat1);
                pfac3 = gsl_complex_mul(pfac3, trace(temp_mat0));
                pfac3 = gsl_complex_mul(pfac3, trace(temp_mat1));
                free(array0);
                free(array1);
                gsl_matrix_complex_free(temp_mat0);
                gsl_matrix_complex_free(temp_mat1);
                res = gsl_complex_add(pfac3, res);
            }
            gsl_complex pfac4 = GSL_COMPLEX_ZERO;
            pfac4 = gsl_complex_add(pfac4, gsl_complex_mul_real(gamma_table[4][uM+nHL*(i2[1]+nHL*(uM+nHL*(i2[0])))], (double)e[i2[0]]*e[uM]*e[i2[1]]+e[uM]+e[uM]+e[i2[0]]*e[uM]*e[i2[1]]));
            pfac4 = gsl_complex_add(pfac4, gsl_complex_mul_real(gamma_table[2][i2[1]+nHL*(i2[0])], (double)e[i2[0]]*e[uM]*e[i2[1]]+2*e[i2[0]]*e[uM]*e[i2[1]]+e[i2[0]]*e[uM]*e[i2[1]]+2*e[i2[0]]*e[uM]*e[i2[1]]));
            if(GSL_REAL(pfac4) != 0. || GSL_IMAG(pfac4) != 0.)
            {
                gsl_matrix_complex** array1 = malloc(3*sizeof(gsl_matrix_complex*));
                array1[0] = MAT[i2[0]];
                array1[1] = dM;
                array1[2] = MAT[i2[1]];
                gsl_matrix_complex* temp_mat1 = gsl_matrix_complex_alloc(dim, dim);
                matrix_multiprod(array1, 3, temp_mat1);
                pfac4 = gsl_complex_mul(pfac4, trace(dM));
                pfac4 = gsl_complex_mul(pfac4, trace(temp_mat1));
                free(array1);
                gsl_matrix_complex_free(temp_mat1);
                res = gsl_complex_add(pfac4, res);
            }
            gsl_complex pfac5 = GSL_COMPLEX_ZERO;
            pfac5 = gsl_complex_add(pfac5, gsl_complex_mul_real(gamma_table[4][uM+nHL*(i2[1]+nHL*(uM+nHL*(i2[0])))], (double)e[i2[1]]*e[uM]+e[i2[0]]*e[uM]+e[i2[0]]*e[uM]+e[i2[1]]*e[uM]+e[i2[1]]*e[uM]+e[i2[0]]*e[uM]+e[i2[0]]*e[uM]+e[i2[1]]*e[uM]));
            pfac5 = gsl_complex_add(pfac5, gsl_complex_mul_real(gamma_table[2][i2[1]+nHL*(i2[0])], (double)e[i2[1]]*e[uM]+e[i2[0]]*e[uM]+2*e[i2[0]]*e[uM]+2*e[i2[1]]*e[uM]+e[i2[1]]*e[uM]+e[i2[0]]*e[uM]+2*e[i2[0]]*e[uM]+2*e[i2[1]]*e[uM]));
            if(GSL_REAL(pfac5) != 0. || GSL_IMAG(pfac5) != 0.)
            {
                gsl_matrix_complex** array0 = malloc(2*sizeof(gsl_matrix_complex*));
                array0[0] = MAT[i2[1]];
                array0[1] = dM;
                gsl_matrix_complex* temp_mat0 = gsl_matrix_complex_alloc(dim, dim);
                matrix_multiprod(array0, 2, temp_mat0);
                gsl_matrix_complex** array1 = malloc(2*sizeof(gsl_matrix_complex*));
                array1[0] = MAT[i2[0]];
                array1[1] = dM;
                gsl_matrix_complex* temp_mat1 = gsl_matrix_complex_alloc(dim, dim);
                matrix_multiprod(array1, 2, temp_mat1);
                pfac5 = gsl_complex_mul(pfac5, trace(temp_mat0));
                pfac5 = gsl_complex_mul(pfac5, trace(temp_mat1));
                free(array0);
                free(array1);
                gsl_matrix_complex_free(temp_mat0);
                gsl_matrix_complex_free(temp_mat1);
                res = gsl_complex_add(pfac5, res);
            }
            gsl_complex pfac6 = GSL_COMPLEX_ZERO;
            pfac6 = gsl_complex_add(pfac6, gsl_complex_mul_real(gamma_table[4][uM+nHL*(i2[1]+nHL*(uM+nHL*(i2[0])))], (double)e[i2[0]]*e[i2[1]]*e[uM]+e[uM]+e[uM]+e[i2[0]]*e[i2[1]]*e[uM]));
            pfac6 = gsl_complex_add(pfac6, gsl_complex_mul_real(gamma_table[2][i2[1]+nHL*(i2[0])], (double)e[uM]+2*e[uM]+e[uM]+2*e[uM]));
            if(GSL_REAL(pfac6) != 0. || GSL_IMAG(pfac6) != 0.)
            {
                gsl_matrix_complex** array1 = malloc(3*sizeof(gsl_matrix_complex*));
                array1[0] = MAT[i2[0]];
                array1[1] = MAT[i2[1]];
                array1[2] = dM;
                gsl_matrix_complex* temp_mat1 = gsl_matrix_complex_alloc(dim, dim);
                matrix_multiprod(array1, 3, temp_mat1);
                pfac6 = gsl_complex_mul(pfac6, trace(dM));
                pfac6 = gsl_complex_mul(pfac6, trace(temp_mat1));
                free(array1);
                gsl_matrix_complex_free(temp_mat1);
                res = gsl_complex_add(pfac6, res);
            }
            gsl_complex pfac7 = GSL_COMPLEX_ZERO;
            pfac7 = gsl_complex_add(pfac7, gsl_complex_mul_real(gamma_table[2][i2[1]+nHL*(i2[0])], (double)dim+dim*e[i2[0]]*e[i2[1]]+dim+dim));
            if(GSL_REAL(pfac7) != 0. || GSL_IMAG(pfac7) != 0.)
            {
                gsl_matrix_complex** array0 = malloc(4*sizeof(gsl_matrix_complex*));
                array0[0] = MAT[i2[0]];
                array0[1] = MAT[i2[1]];
                array0[2] = dM;
                array0[3] = dM;
                gsl_matrix_complex* temp_mat0 = gsl_matrix_complex_alloc(dim, dim);
                matrix_multiprod(array0, 4, temp_mat0);
                pfac7 = gsl_complex_mul(pfac7, trace(temp_mat0));
                free(array0);
                gsl_matrix_complex_free(temp_mat0);
                res = gsl_complex_add(pfac7, res);
            }
            gsl_complex pfac8 = GSL_COMPLEX_ZERO;
            pfac8 = gsl_complex_add(pfac8, gsl_complex_mul_real(gamma_table[4][uM+nHL*(i2[1]+nHL*(uM+nHL*(i2[0])))], (double)dim*e[i2[0]]*e[i2[1]]+dim+dim+dim*e[i2[0]]*e[i2[1]]));
            if(GSL_REAL(pfac8) != 0. || GSL_IMAG(pfac8) != 0.)
            {
                gsl_matrix_complex** array0 = malloc(4*sizeof(gsl_matrix_complex*));
                array0[0] = MAT[i2[0]];
                array0[1] = dM;
                array0[2] = MAT[i2[1]];
                array0[3] = dM;
                gsl_matrix_complex* temp_mat0 = gsl_matrix_complex_alloc(dim, dim);
                matrix_multiprod(array0, 4, temp_mat0);
                pfac8 = gsl_complex_mul(pfac8, trace(temp_mat0));
                free(array0);
                gsl_matrix_complex_free(temp_mat0);
                res = gsl_complex_add(pfac8, res);
            }
            gsl_complex pfac9 = GSL_COMPLEX_ZERO;
            pfac9 = gsl_complex_add(pfac9, gsl_complex_mul_real(gamma_table[2][i2[1]+nHL*(i2[0])], (double)e[i2[1]]+e[i2[0]]));
            pfac9 = gsl_complex_add(pfac9, gsl_complex_mul_real(gamma_table[4][uM+nHL*(i2[1]+nHL*(uM+nHL*(i2[0])))], (double)e[i2[0]]+e[i2[1]]));
            if(GSL_REAL(pfac9) != 0. || GSL_IMAG(pfac9) != 0.)
            {
                gsl_matrix_complex** array0 = malloc(3*sizeof(gsl_matrix_complex*));
                array0[0] = MAT[i2[1]];
                array0[1] = dM;
                array0[2] = dM;
                gsl_matrix_complex* temp_mat0 = gsl_matrix_complex_alloc(dim, dim);
                matrix_multiprod(array0, 3, temp_mat0);
                pfac9 = gsl_complex_mul(pfac9, trace(temp_mat0));
                pfac9 = gsl_complex_mul(pfac9, trace(MAT[i2[0]]));
                free(array0);
                gsl_matrix_complex_free(temp_mat0);
                res = gsl_complex_add(pfac9, res);
            }
            gsl_complex pfac10 = GSL_COMPLEX_ZERO;
            pfac10 = gsl_complex_add(pfac10, gsl_complex_mul_real(gamma_table[2][i2[1]+nHL*(i2[0])], (double)e[i2[0]]+e[i2[1]]));
            pfac10 = gsl_complex_add(pfac10, gsl_complex_mul_real(gamma_table[4][uM+nHL*(i2[1]+nHL*(uM+nHL*(i2[0])))], (double)e[i2[1]]+e[i2[0]]));
            if(GSL_REAL(pfac10) != 0. || GSL_IMAG(pfac10) != 0.)
            {
                gsl_matrix_complex** array1 = malloc(3*sizeof(gsl_matrix_complex*));
                array1[0] = MAT[i2[0]];
                array1[1] = dM;
                array1[2] = dM;
                gsl_matrix_complex* temp_mat1 = gsl_matrix_complex_alloc(dim, dim);
                matrix_multiprod(array1, 3, temp_mat1);
                pfac10 = gsl_complex_mul(pfac10, trace(MAT[i2[1]]));
                pfac10 = gsl_complex_mul(pfac10, trace(temp_mat1));
                free(array1);
                gsl_matrix_complex_free(temp_mat1);
                res = gsl_complex_add(pfac10, res);
            }
            gsl_complex pfac11 = GSL_COMPLEX_ZERO;
            pfac11 = gsl_complex_add(pfac11, gsl_complex_mul_real(gamma_table[2][i2[1]+nHL*(i2[0])], (double)1+e[i2[0]]*e[i2[1]]));
            pfac11 = gsl_complex_add(pfac11, gsl_complex_mul_real(gamma_table[4][uM+nHL*(i2[1]+nHL*(uM+nHL*(i2[0])))], (double)e[i2[0]]*e[i2[1]]+1));
            if(GSL_REAL(pfac11) != 0. || GSL_IMAG(pfac11) != 0.)
            {
                gsl_matrix_complex** array0 = malloc(2*sizeof(gsl_matrix_complex*));
                array0[0] = dM;
                array0[1] = dM;
                gsl_matrix_complex* temp_mat0 = gsl_matrix_complex_alloc(dim, dim);
                matrix_multiprod(array0, 2, temp_mat0);
                gsl_matrix_complex** array1 = malloc(2*sizeof(gsl_matrix_complex*));
                array1[0] = MAT[i2[0]];
                array1[1] = MAT[i2[1]];
                gsl_matrix_complex* temp_mat1 = gsl_matrix_complex_alloc(dim, dim);
                matrix_multiprod(array1, 2, temp_mat1);
                pfac11 = gsl_complex_mul(pfac11, trace(temp_mat0));
                pfac11 = gsl_complex_mul(pfac11, trace(temp_mat1));
                free(array0);
                free(array1);
                gsl_matrix_complex_free(temp_mat0);
                gsl_matrix_complex_free(temp_mat1);
                res = gsl_complex_add(pfac11, res);
            }
            gsl_complex pfac12 = GSL_COMPLEX_ZERO;
            pfac12 = gsl_complex_add(pfac12, gsl_complex_mul_real(gamma_table[2][i2[1]+nHL*(i2[0])], (double)2*e[i2[0]]*e[i2[1]]*e[uM]));
            if(GSL_REAL(pfac12) != 0. || GSL_IMAG(pfac12) != 0.)
            {
                gsl_matrix_complex** array1 = malloc(3*sizeof(gsl_matrix_complex*));
                array1[0] = MAT[i2[0]];
                array1[1] = MAT[i2[1]];
                array1[2] = dM;
                gsl_matrix_complex* temp_mat1 = gsl_matrix_complex_alloc(dim, dim);
                matrix_multiprod(array1, 3, temp_mat1);
                pfac12 = gsl_complex_mul(pfac12, trace(dM));
                pfac12 = gsl_complex_mul(pfac12, trace(temp_mat1));
                free(array1);
                gsl_matrix_complex_free(temp_mat1);
                res = gsl_complex_add(pfac12, res);
            }
            gsl_complex pfac13 = GSL_COMPLEX_ZERO;
            pfac13 = gsl_complex_add(pfac13, gsl_complex_mul_real(gamma_table[2][i2[1]+nHL*(i2[0])], (double)2*e[i2[0]]*e[uM]+2*e[i2[1]]*e[uM]));
            if(GSL_REAL(pfac13) != 0. || GSL_IMAG(pfac13) != 0.)
            {
                gsl_matrix_complex** array0 = malloc(2*sizeof(gsl_matrix_complex*));
                array0[0] = MAT[i2[1]];
                array0[1] = dM;
                gsl_matrix_complex* temp_mat0 = gsl_matrix_complex_alloc(dim, dim);
                matrix_multiprod(array0, 2, temp_mat0);
                gsl_matrix_complex** array1 = malloc(2*sizeof(gsl_matrix_complex*));
                array1[0] = MAT[i2[0]];
                array1[1] = dM;
                gsl_matrix_complex* temp_mat1 = gsl_matrix_complex_alloc(dim, dim);
                matrix_multiprod(array1, 2, temp_mat1);
                pfac13 = gsl_complex_mul(pfac13, trace(temp_mat0));
                pfac13 = gsl_complex_mul(pfac13, trace(temp_mat1));
                free(array0);
                free(array1);
                gsl_matrix_complex_free(temp_mat0);
                gsl_matrix_complex_free(temp_mat1);
                res = gsl_complex_add(pfac13, res);
            }
            gsl_complex pfac14 = GSL_COMPLEX_ZERO;
            pfac14 = gsl_complex_add(pfac14, gsl_complex_mul_real(gamma_table[2][i2[1]+nHL*(i2[0])], (double)2*e[uM]));
            if(GSL_REAL(pfac14) != 0. || GSL_IMAG(pfac14) != 0.)
            {
                gsl_matrix_complex** array1 = malloc(3*sizeof(gsl_matrix_complex*));
                array1[0] = MAT[i2[0]];
                array1[1] = dM;
                array1[2] = MAT[i2[1]];
                gsl_matrix_complex* temp_mat1 = gsl_matrix_complex_alloc(dim, dim);
                matrix_multiprod(array1, 3, temp_mat1);
                pfac14 = gsl_complex_mul(pfac14, trace(dM));
                pfac14 = gsl_complex_mul(pfac14, trace(temp_mat1));
                free(array1);
                gsl_matrix_complex_free(temp_mat1);
                res = gsl_complex_add(pfac14, res);
            }
        }
    }
    free(i2);



    // CASE: s=3

    int* i3 = malloc(1*sizeof(int));
    for(i3[0]=0; i3[0]<nHL; i3[0]++)
    {
        gsl_complex pfac0 = GSL_COMPLEX_ZERO;
        pfac0 = gsl_complex_add(pfac0, gsl_complex_mul_real(gamma_table[2][uM+nHL*(i3[0])], (double)dim*e[i3[0]]*e[uM]+dim+dim+dim*e[i3[0]]*e[uM]+dim*e[i3[0]]*e[uM]+dim+dim+dim*e[i3[0]]*e[uM]));
        if(GSL_REAL(pfac0) != 0. || GSL_IMAG(pfac0) != 0.)
        {
            gsl_matrix_complex** array0 = malloc(4*sizeof(gsl_matrix_complex*));
            array0[0] = MAT[i3[0]];
            array0[1] = dM;
            array0[2] = dM;
            array0[3] = dM;
            gsl_matrix_complex* temp_mat0 = gsl_matrix_complex_alloc(dim, dim);
            matrix_multiprod(array0, 4, temp_mat0);
            pfac0 = gsl_complex_mul(pfac0, trace(temp_mat0));
            free(array0);
            gsl_matrix_complex_free(temp_mat0);
            res = gsl_complex_add(pfac0, res);
        }
        gsl_complex pfac1 = GSL_COMPLEX_ZERO;
        pfac1 = gsl_complex_add(pfac1, gsl_complex_mul_real(gamma_table[2][uM+nHL*(i3[0])], (double)e[uM]+e[i3[0]]+e[i3[0]]+e[uM]+e[uM]+e[i3[0]]+e[i3[0]]+e[uM]));
        if(GSL_REAL(pfac1) != 0. || GSL_IMAG(pfac1) != 0.)
        {
            gsl_matrix_complex** array0 = malloc(3*sizeof(gsl_matrix_complex*));
            array0[0] = dM;
            array0[1] = dM;
            array0[2] = dM;
            gsl_matrix_complex* temp_mat0 = gsl_matrix_complex_alloc(dim, dim);
            matrix_multiprod(array0, 3, temp_mat0);
            pfac1 = gsl_complex_mul(pfac1, trace(temp_mat0));
            pfac1 = gsl_complex_mul(pfac1, trace(MAT[i3[0]]));
            free(array0);
            gsl_matrix_complex_free(temp_mat0);
            res = gsl_complex_add(pfac1, res);
        }
        gsl_complex pfac2 = GSL_COMPLEX_ZERO;
        pfac2 = gsl_complex_add(pfac2, gsl_complex_mul_real(gamma_table[2][uM+nHL*(i3[0])], (double)e[i3[0]]+2*e[uM]+2*e[i3[0]]+e[i3[0]]+2*e[i3[0]]+e[uM]+3*e[uM]+3*e[i3[0]]));
        if(GSL_REAL(pfac2) != 0. || GSL_IMAG(pfac2) != 0.)
        {
            gsl_matrix_complex** array1 = malloc(3*sizeof(gsl_matrix_complex*));
            array1[0] = MAT[i3[0]];
            array1[1] = dM;
            array1[2] = dM;
            gsl_matrix_complex* temp_mat1 = gsl_matrix_complex_alloc(dim, dim);
            matrix_multiprod(array1, 3, temp_mat1);
            pfac2 = gsl_complex_mul(pfac2, trace(dM));
            pfac2 = gsl_complex_mul(pfac2, trace(temp_mat1));
            free(array1);
            gsl_matrix_complex_free(temp_mat1);
            res = gsl_complex_add(pfac2, res);
        }
        gsl_complex pfac3 = GSL_COMPLEX_ZERO;
        pfac3 = gsl_complex_add(pfac3, gsl_complex_mul_real(gamma_table[2][uM+nHL*(i3[0])], (double)1+2*e[i3[0]]*e[uM]+2+1+2+e[i3[0]]*e[uM]+3*e[i3[0]]*e[uM]+3));
        if(GSL_REAL(pfac3) != 0. || GSL_IMAG(pfac3) != 0.)
        {
            gsl_matrix_complex** array0 = malloc(2*sizeof(gsl_matrix_complex*));
            array0[0] = dM;
            array0[1] = dM;
            gsl_matrix_complex* temp_mat0 = gsl_matrix_complex_alloc(dim, dim);
            matrix_multiprod(array0, 2, temp_mat0);
            gsl_matrix_complex** array1 = malloc(2*sizeof(gsl_matrix_complex*));
            array1[0] = MAT[i3[0]];
            array1[1] = dM;
            gsl_matrix_complex* temp_mat1 = gsl_matrix_complex_alloc(dim, dim);
            matrix_multiprod(array1, 2, temp_mat1);
            pfac3 = gsl_complex_mul(pfac3, trace(temp_mat0));
            pfac3 = gsl_complex_mul(pfac3, trace(temp_mat1));
            free(array0);
            free(array1);
            gsl_matrix_complex_free(temp_mat0);
            gsl_matrix_complex_free(temp_mat1);
            res = gsl_complex_add(pfac3, res);
        }
        gsl_complex pfac4 = GSL_COMPLEX_ZERO;
        pfac4 = gsl_complex_add(pfac4, gsl_complex_mul_real(gamma_table[2][uM+nHL*(i3[0])], (double)3+3*e[i3[0]]*e[uM]+e[i3[0]]*e[uM]+2*e[i3[0]]*e[uM]));
        if(GSL_REAL(pfac4) != 0. || GSL_IMAG(pfac4) != 0.)
        {
            gsl_matrix_complex** array0 = malloc(2*sizeof(gsl_matrix_complex*));
            array0[0] = dM;
            array0[1] = dM;
            gsl_matrix_complex* temp_mat0 = gsl_matrix_complex_alloc(dim, dim);
            matrix_multiprod(array0, 2, temp_mat0);
            gsl_matrix_complex** array1 = malloc(2*sizeof(gsl_matrix_complex*));
            array1[0] = MAT[i3[0]];
            array1[1] = dM;
            gsl_matrix_complex* temp_mat1 = gsl_matrix_complex_alloc(dim, dim);
            matrix_multiprod(array1, 2, temp_mat1);
            pfac4 = gsl_complex_mul(pfac4, trace(temp_mat0));
            pfac4 = gsl_complex_mul(pfac4, trace(temp_mat1));
            free(array0);
            free(array1);
            gsl_matrix_complex_free(temp_mat0);
            gsl_matrix_complex_free(temp_mat1);
            res = gsl_complex_add(pfac4, res);
        }
        gsl_complex pfac5 = GSL_COMPLEX_ZERO;
        pfac5 = gsl_complex_add(pfac5, gsl_complex_mul_real(gamma_table[2][uM+nHL*(i3[0])], (double)3*e[i3[0]]+3*e[uM]+e[uM]+2*e[uM]));
        if(GSL_REAL(pfac5) != 0. || GSL_IMAG(pfac5) != 0.)
        {
            gsl_matrix_complex** array1 = malloc(3*sizeof(gsl_matrix_complex*));
            array1[0] = MAT[i3[0]];
            array1[1] = dM;
            array1[2] = dM;
            gsl_matrix_complex* temp_mat1 = gsl_matrix_complex_alloc(dim, dim);
            matrix_multiprod(array1, 3, temp_mat1);
            pfac5 = gsl_complex_mul(pfac5, trace(dM));
            pfac5 = gsl_complex_mul(pfac5, trace(temp_mat1));
            free(array1);
            gsl_matrix_complex_free(temp_mat1);
            res = gsl_complex_add(pfac5, res);
        }
    }
    free(i3);



    // CASE: s=4

    gsl_complex pfac0 = GSL_COMPLEX_ZERO;
    pfac0 = gsl_complex_add(pfac0, gsl_complex_mul_real(gsl_complex_rect(dimG, 0.), (double)dim+dim));
    if(GSL_REAL(pfac0) != 0. || GSL_IMAG(pfac0) != 0.)
    {
        gsl_matrix_complex** array0 = malloc(4*sizeof(gsl_matrix_complex*));
        array0[0] = dM;
        array0[1] = dM;
        array0[2] = dM;
        array0[3] = dM;
        gsl_matrix_complex* temp_mat0 = gsl_matrix_complex_alloc(dim, dim);
        matrix_multiprod(array0, 4, temp_mat0);
        pfac0 = gsl_complex_mul(pfac0, trace(temp_mat0));
        free(array0);
        gsl_matrix_complex_free(temp_mat0);
        res = gsl_complex_add(pfac0, res);
    }
    gsl_complex pfac1 = GSL_COMPLEX_ZERO;
    pfac1 = gsl_complex_add(pfac1, gsl_complex_mul_real(gsl_complex_rect(dimG, 0.), (double)4*e[uM]+4*e[uM]));
    if(GSL_REAL(pfac1) != 0. || GSL_IMAG(pfac1) != 0.)
    {
        gsl_matrix_complex** array0 = malloc(3*sizeof(gsl_matrix_complex*));
        array0[0] = dM;
        array0[1] = dM;
        array0[2] = dM;
        gsl_matrix_complex* temp_mat0 = gsl_matrix_complex_alloc(dim, dim);
        matrix_multiprod(array0, 3, temp_mat0);
        pfac1 = gsl_complex_mul(pfac1, trace(temp_mat0));
        pfac1 = gsl_complex_mul(pfac1, trace(dM));
        free(array0);
        gsl_matrix_complex_free(temp_mat0);
        res = gsl_complex_add(pfac1, res);
    }
    gsl_complex pfac2 = GSL_COMPLEX_ZERO;
    pfac2 = gsl_complex_add(pfac2, gsl_complex_mul_real(gsl_complex_rect(dimG, 0.), (double)6));
    if(GSL_REAL(pfac2) != 0. || GSL_IMAG(pfac2) != 0.)
    {
        gsl_matrix_complex** array0 = malloc(2*sizeof(gsl_matrix_complex*));
        array0[0] = dM;
        array0[1] = dM;
        gsl_matrix_complex* temp_mat0 = gsl_matrix_complex_alloc(dim, dim);
        matrix_multiprod(array0, 2, temp_mat0);
        gsl_matrix_complex** array1 = malloc(2*sizeof(gsl_matrix_complex*));
        array1[0] = dM;
        array1[1] = dM;
        gsl_matrix_complex* temp_mat1 = gsl_matrix_complex_alloc(dim, dim);
        matrix_multiprod(array1, 2, temp_mat1);
        pfac2 = gsl_complex_mul(pfac2, trace(temp_mat0));
        pfac2 = gsl_complex_mul(pfac2, trace(temp_mat1));
        free(array0);
        free(array1);
        gsl_matrix_complex_free(temp_mat0);
        gsl_matrix_complex_free(temp_mat1);
        res = gsl_complex_add(pfac2, res);
    }



    return GSL_REAL(res);
}

