#define ACTION_C

#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <gsl/gsl_rng.h>
#include <gsl/gsl_complex.h>
#include <gsl/gsl_vector_double.h>
#include "update.h"
#include "matop.h"
#include "fileop.h"
#include "math.h"
#include <gsl/gsl_randist.h>
#include <gsl/gsl_sort_vector.h>
#include <gsl/gsl_blas.h>
#include "global.h"
#include "macros.h"
#include "data.h"
#include "statistics.h"


double delta2(gsl_matrix_complex* dM, int uM)
{

    gsl_complex res = GSL_COMPLEX_ZERO;


    // CASE: s=1

    for(int i=0; i<nHL; i++)
    {
        // trace of the clifford part
        gsl_matrix_complex* m = gsl_matrix_complex_alloc(dimG, dimG);
        gsl_blas_zgemm(CblasNoTrans, CblasNoTrans, GSL_COMPLEX_ONE, gamma[uM], gamma[i], GSL_COMPLEX_ZERO, m);
        gsl_complex A = trace(m);
        A = gsl_complex_mul_real(A, 4.);
        
        gsl_matrix_complex_free(m);

        if(GSL_REAL(A) != 0 || GSL_IMAG(A) != 0)
        {
            gsl_complex B;
            gsl_complex C;
            B = gsl_complex_mul(trace(dM), trace(MAT[i]));

            gsl_matrix_complex* m1 = gsl_matrix_complex_alloc(dim, dim);
            gsl_blas_zgemm(CblasNoTrans, CblasNoTrans, GSL_COMPLEX_ONE, dM, MAT[i], GSL_COMPLEX_ZERO, m1);
            C = trace(m1);
            gsl_matrix_complex_free(m1);

            if(uM < nH && i < nH)
                C = gsl_complex_mul_real(C, (double)dim);
            
            else if(uM >= nH && i >= nH)
                C = gsl_complex_mul_real(C, (double)(-dim));

            B = gsl_complex_add(B, C);
            A = gsl_complex_mul(A, B);

            res = gsl_complex_add(res, A);
        }
    }


    // CASE: s=2

    gsl_matrix_complex* m2 = gsl_matrix_complex_alloc(dim, dim);
    gsl_blas_zgemm(CblasNoTrans, CblasNoTrans, GSL_COMPLEX_ONE, dM, dM, GSL_COMPLEX_ZERO, m2);
    gsl_complex A = trace(m2);
    A = gsl_complex_mul_real(A, (double)dim);
    gsl_matrix_complex_free(m2);
    gsl_complex B = trace(dM);
    B = gsl_complex_mul(B, B);
    if(uM < nH)
        A = gsl_complex_add(A, B);
    else
        A = gsl_complex_sub(A, B);
    A = gsl_complex_mul_real(A, 2.*dimG);

    res = gsl_complex_add(res, A);

    //printf("%.15lf %.15lf\n", GSL_REAL(res), GSL_IMAG(res));

    return GSL_REAL(res);
}

double delta2_auto(gsl_matrix_complex* dM, int uM)
{
    // THIS CODE IS GENERATED BY delta.py SCRIPT (in the script folder)

    gsl_complex pfac;
    int jfac;
    gsl_complex res = GSL_COMPLEX_ZERO;

    // CASE: s=1

    int* i1 = malloc(1*sizeof(int));
    for(i1[0]=0; i1[0]<nHL; i1[0]++)
    {
        gsl_matrix_complex** array10 = malloc(2*sizeof(gsl_matrix_complex*));
        array10[0] = gamma[i1[0]];
        array10[1] = gamma[uM];
        gsl_matrix_complex* gamma_i1_0__gamma_uM_ = gsl_matrix_complex_alloc(dimG, dimG);
        matrix_multiprod(array10, 2, gamma_i1_0__gamma_uM_);
        gsl_complex trgamma_i1_0__gamma_uM_ = trace(gamma_i1_0__gamma_uM_);
        gsl_matrix_complex_free(gamma_i1_0__gamma_uM_);
        free(array10);
        gsl_matrix_complex** array11 = malloc(2*sizeof(gsl_matrix_complex*));
        array11[0] = MAT[i1[0]];
        array11[1] = dM;
        gsl_matrix_complex* MAT_i1_0__dM = gsl_matrix_complex_alloc(dim, dim);
        matrix_multiprod(array11, 2, MAT_i1_0__dM);
        gsl_complex trMAT_i1_0__dM = trace(MAT_i1_0__dM);
        gsl_matrix_complex_free(MAT_i1_0__dM);
        free(array11);
        gsl_complex trMAT_i1_0__ = trace(MAT[i1[0]]);
        gsl_complex trdM = trace(dM);
        jfac = (int)(0.5*(2-1*e[uM]-e[i1[0]])) % 4;
        if(jfac == 0)
            pfac = gsl_complex_rect(dim*(1*e[uM]*e[i1[0]]+1*1+1*e[uM]*e[i1[0]]+1*1), 0);
        if(jfac == 1)
            pfac = gsl_complex_rect(0, dim*(1*e[uM]*e[i1[0]]+1*1+1*e[uM]*e[i1[0]]+1*1));
        if(jfac == 2)
            pfac = gsl_complex_rect(-dim*(1*e[uM]*e[i1[0]]+1*1+1*e[uM]*e[i1[0]]+1*1), 0);
        if(jfac == 3)
            pfac = gsl_complex_rect(0, -dim*(1*e[uM]*e[i1[0]]+1*1+1*e[uM]*e[i1[0]]+1*1));
        res = gsl_complex_add(res, gsl_complex_mul(gsl_complex_mul(trgamma_i1_0__gamma_uM_, trMAT_i1_0__dM), pfac));
        jfac = (int)(0.5*(2-1*e[uM]-e[i1[0]])) % 4;
        if(jfac == 0)
            pfac = gsl_complex_rect(1*e[uM]+1*e[i1[0]]+1*e[uM]+1*e[i1[0]], 0);
        if(jfac == 1)
            pfac = gsl_complex_rect(0, 1*e[uM]+1*e[i1[0]]+1*e[uM]+1*e[i1[0]]);
        if(jfac == 2)
            pfac = gsl_complex_rect(-1*e[uM]+1*e[i1[0]]+1*e[uM]+1*e[i1[0]], 0);
        if(jfac == 3)
            pfac = gsl_complex_rect(0, -1*e[uM]+1*e[i1[0]]+1*e[uM]+1*e[i1[0]]);
        res = gsl_complex_add(res, gsl_complex_mul(gsl_complex_mul(gsl_complex_mul(trgamma_i1_0__gamma_uM_, trMAT_i1_0__), trdM), pfac));
    }
    free(i1);



    // CASE: s=2

    gsl_matrix_complex** array20 = malloc(2*sizeof(gsl_matrix_complex*));
    array20[0] = dM;
    array20[1] = dM;
    gsl_matrix_complex* dMdM = gsl_matrix_complex_alloc(dim, dim);
    matrix_multiprod(array20, 2, dMdM);
    gsl_complex trdMdM = trace(dMdM);
    gsl_matrix_complex_free(dMdM);
    free(array20);
    gsl_complex trdM = trace(dM);
    jfac = (int)(0.5*(2-2*e[uM]-0)) % 4;
    if(jfac == 0)
        pfac = gsl_complex_rect(dimG*dim*(1*1*e[uM]+1*1*e[uM]), 0);
    if(jfac == 1)
        pfac = gsl_complex_rect(0, dimG*dim*(1*1*e[uM]+1*1*e[uM]));
    if(jfac == 2)
        pfac = gsl_complex_rect(-dimG*dim*(1*1*e[uM]+1*1*e[uM]), 0);
    if(jfac == 3)
        pfac = gsl_complex_rect(0, -dimG*dim*(1*1*e[uM]+1*1*e[uM]));
    res = gsl_complex_add(res, gsl_complex_mul(trdMdM, pfac));
    jfac = (int)(0.5*(2-2*e[uM]-0)) % 4;
    if(jfac == 0)
        pfac = gsl_complex_rect(dimG*(2*1), 0);
    if(jfac == 1)
        pfac = gsl_complex_rect(0, dimG*(2*1));
    if(jfac == 2)
        pfac = gsl_complex_rect(-dimG*(2*1), 0);
    if(jfac == 3)
        pfac = gsl_complex_rect(0, -dimG*(2*1));
    res = gsl_complex_add(res, gsl_complex_mul(gsl_complex_mul(trdM, trdM), pfac));



    return GSL_REAL(res);
}


//printf("%.20lf\n", GSL_IMAG(res));
double delta4(gsl_matrix_complex* dM, int uM)
{
    // THIS CODE IS GENERATED BY delta.py SCRIPT (in the script folder)

    gsl_complex pfac;
    double jfac_d;
    int jfac_i;
    gsl_complex res = GSL_COMPLEX_ZERO;

    // CASE: s=1

    int* i1 = malloc(3*sizeof(int));
    for(i1[0]=0; i1[0]<nHL; i1[0]++)
    {
        for(i1[1]=0; i1[1]<nHL; i1[1]++)
        {
            for(i1[2]=0; i1[2]<nHL; i1[2]++)
            {
                gsl_matrix_complex** array10 = malloc(4*sizeof(gsl_matrix_complex*));
                array10[0] = gamma[i1[0]];
                array10[1] = gamma[i1[1]];
                array10[2] = gamma[i1[2]];
                array10[3] = gamma[uM];
                gsl_matrix_complex* gamma_i1_0__gamma_i1_1__gamma_i1_2__gamma_uM_ = gsl_matrix_complex_alloc(dimG, dimG);
                matrix_multiprod(array10, 4, gamma_i1_0__gamma_i1_1__gamma_i1_2__gamma_uM_);
                gsl_complex trgamma_i1_0__gamma_i1_1__gamma_i1_2__gamma_uM_ = trace(gamma_i1_0__gamma_i1_1__gamma_i1_2__gamma_uM_);
                gsl_matrix_complex_free(gamma_i1_0__gamma_i1_1__gamma_i1_2__gamma_uM_);
                free(array10);
                gsl_matrix_complex** array11 = malloc(4*sizeof(gsl_matrix_complex*));
                array11[0] = MAT[i1[0]];
                array11[1] = dM;
                array11[2] = MAT[i1[2]];
                array11[3] = MAT[i1[1]];
                gsl_matrix_complex* MAT_i1_0__dMMAT_i1_2__MAT_i1_1__ = gsl_matrix_complex_alloc(dim, dim);
                matrix_multiprod(array11, 4, MAT_i1_0__dMMAT_i1_2__MAT_i1_1__);
                gsl_complex trMAT_i1_0__dMMAT_i1_2__MAT_i1_1__ = trace(MAT_i1_0__dMMAT_i1_2__MAT_i1_1__);
                gsl_matrix_complex_free(MAT_i1_0__dMMAT_i1_2__MAT_i1_1__);
                free(array11);
                gsl_complex trMAT_i1_0__ = trace(MAT[i1[0]]);
                gsl_matrix_complex** array13 = malloc(3*sizeof(gsl_matrix_complex*));
                array13[0] = MAT[i1[1]];
                array13[1] = dM;
                array13[2] = MAT[i1[2]];
                gsl_matrix_complex* MAT_i1_1__dMMAT_i1_2__ = gsl_matrix_complex_alloc(dim, dim);
                matrix_multiprod(array13, 3, MAT_i1_1__dMMAT_i1_2__);
                gsl_complex trMAT_i1_1__dMMAT_i1_2__ = trace(MAT_i1_1__dMMAT_i1_2__);
                gsl_matrix_complex_free(MAT_i1_1__dMMAT_i1_2__);
                free(array13);
                gsl_matrix_complex** array14 = malloc(3*sizeof(gsl_matrix_complex*));
                array14[0] = MAT[i1[0]];
                array14[1] = dM;
                array14[2] = MAT[i1[2]];
                gsl_matrix_complex* MAT_i1_0__dMMAT_i1_2__ = gsl_matrix_complex_alloc(dim, dim);
                matrix_multiprod(array14, 3, MAT_i1_0__dMMAT_i1_2__);
                gsl_complex trMAT_i1_0__dMMAT_i1_2__ = trace(MAT_i1_0__dMMAT_i1_2__);
                gsl_matrix_complex_free(MAT_i1_0__dMMAT_i1_2__);
                free(array14);
                gsl_complex trMAT_i1_1__ = trace(MAT[i1[1]]);
                gsl_matrix_complex** array16 = malloc(2*sizeof(gsl_matrix_complex*));
                array16[0] = MAT[i1[0]];
                array16[1] = MAT[i1[1]];
                gsl_matrix_complex* MAT_i1_0__MAT_i1_1__ = gsl_matrix_complex_alloc(dim, dim);
                matrix_multiprod(array16, 2, MAT_i1_0__MAT_i1_1__);
                gsl_complex trMAT_i1_0__MAT_i1_1__ = trace(MAT_i1_0__MAT_i1_1__);
                gsl_matrix_complex_free(MAT_i1_0__MAT_i1_1__);
                free(array16);
                gsl_matrix_complex** array17 = malloc(2*sizeof(gsl_matrix_complex*));
                array17[0] = MAT[i1[2]];
                array17[1] = dM;
                gsl_matrix_complex* MAT_i1_2__dM = gsl_matrix_complex_alloc(dim, dim);
                matrix_multiprod(array17, 2, MAT_i1_2__dM);
                gsl_complex trMAT_i1_2__dM = trace(MAT_i1_2__dM);
                gsl_matrix_complex_free(MAT_i1_2__dM);
                free(array17);
                gsl_matrix_complex** array18 = malloc(3*sizeof(gsl_matrix_complex*));
                array18[0] = MAT[i1[0]];
                array18[1] = dM;
                array18[2] = MAT[i1[1]];
                gsl_matrix_complex* MAT_i1_0__dMMAT_i1_1__ = gsl_matrix_complex_alloc(dim, dim);
                matrix_multiprod(array18, 3, MAT_i1_0__dMMAT_i1_1__);
                gsl_complex trMAT_i1_0__dMMAT_i1_1__ = trace(MAT_i1_0__dMMAT_i1_1__);
                gsl_matrix_complex_free(MAT_i1_0__dMMAT_i1_1__);
                free(array18);
                gsl_complex trMAT_i1_2__ = trace(MAT[i1[2]]);
                gsl_matrix_complex** array110 = malloc(2*sizeof(gsl_matrix_complex*));
                array110[0] = MAT[i1[0]];
                array110[1] = MAT[i1[2]];
                gsl_matrix_complex* MAT_i1_0__MAT_i1_2__ = gsl_matrix_complex_alloc(dim, dim);
                matrix_multiprod(array110, 2, MAT_i1_0__MAT_i1_2__);
                gsl_complex trMAT_i1_0__MAT_i1_2__ = trace(MAT_i1_0__MAT_i1_2__);
                gsl_matrix_complex_free(MAT_i1_0__MAT_i1_2__);
                free(array110);
                gsl_matrix_complex** array111 = malloc(2*sizeof(gsl_matrix_complex*));
                array111[0] = MAT[i1[1]];
                array111[1] = dM;
                gsl_matrix_complex* MAT_i1_1__dM = gsl_matrix_complex_alloc(dim, dim);
                matrix_multiprod(array111, 2, MAT_i1_1__dM);
                gsl_complex trMAT_i1_1__dM = trace(MAT_i1_1__dM);
                gsl_matrix_complex_free(MAT_i1_1__dM);
                free(array111);
                gsl_matrix_complex** array112 = malloc(2*sizeof(gsl_matrix_complex*));
                array112[0] = MAT[i1[0]];
                array112[1] = dM;
                gsl_matrix_complex* MAT_i1_0__dM = gsl_matrix_complex_alloc(dim, dim);
                matrix_multiprod(array112, 2, MAT_i1_0__dM);
                gsl_complex trMAT_i1_0__dM = trace(MAT_i1_0__dM);
                gsl_matrix_complex_free(MAT_i1_0__dM);
                free(array112);
                gsl_matrix_complex** array113 = malloc(2*sizeof(gsl_matrix_complex*));
                array113[0] = MAT[i1[1]];
                array113[1] = MAT[i1[2]];
                gsl_matrix_complex* MAT_i1_1__MAT_i1_2__ = gsl_matrix_complex_alloc(dim, dim);
                matrix_multiprod(array113, 2, MAT_i1_1__MAT_i1_2__);
                gsl_complex trMAT_i1_1__MAT_i1_2__ = trace(MAT_i1_1__MAT_i1_2__);
                gsl_matrix_complex_free(MAT_i1_1__MAT_i1_2__);
                free(array113);
                gsl_matrix_complex** array114 = malloc(3*sizeof(gsl_matrix_complex*));
                array114[0] = MAT[i1[0]];
                array114[1] = MAT[i1[1]];
                array114[2] = MAT[i1[2]];
                gsl_matrix_complex* MAT_i1_0__MAT_i1_1__MAT_i1_2__ = gsl_matrix_complex_alloc(dim, dim);
                matrix_multiprod(array114, 3, MAT_i1_0__MAT_i1_1__MAT_i1_2__);
                gsl_complex trMAT_i1_0__MAT_i1_1__MAT_i1_2__ = trace(MAT_i1_0__MAT_i1_1__MAT_i1_2__);
                gsl_matrix_complex_free(MAT_i1_0__MAT_i1_1__MAT_i1_2__);
                free(array114);
                gsl_complex trdM = trace(dM);
                gsl_matrix_complex** array116 = malloc(3*sizeof(gsl_matrix_complex*));
                array116[0] = MAT[i1[0]];
                array116[1] = MAT[i1[2]];
                array116[2] = MAT[i1[1]];
                gsl_matrix_complex* MAT_i1_0__MAT_i1_2__MAT_i1_1__ = gsl_matrix_complex_alloc(dim, dim);
                matrix_multiprod(array116, 3, MAT_i1_0__MAT_i1_2__MAT_i1_1__);
                gsl_complex trMAT_i1_0__MAT_i1_2__MAT_i1_1__ = trace(MAT_i1_0__MAT_i1_2__MAT_i1_1__);
                gsl_matrix_complex_free(MAT_i1_0__MAT_i1_2__MAT_i1_1__);
                free(array116);
                gsl_matrix_complex** array117 = malloc(3*sizeof(gsl_matrix_complex*));
                array117[0] = MAT[i1[0]];
                array117[1] = MAT[i1[1]];
                array117[2] = dM;
                gsl_matrix_complex* MAT_i1_0__MAT_i1_1__dM = gsl_matrix_complex_alloc(dim, dim);
                matrix_multiprod(array117, 3, MAT_i1_0__MAT_i1_1__dM);
                gsl_complex trMAT_i1_0__MAT_i1_1__dM = trace(MAT_i1_0__MAT_i1_1__dM);
                gsl_matrix_complex_free(MAT_i1_0__MAT_i1_1__dM);
                free(array117);
                gsl_matrix_complex** array118 = malloc(3*sizeof(gsl_matrix_complex*));
                array118[0] = MAT[i1[0]];
                array118[1] = MAT[i1[2]];
                array118[2] = dM;
                gsl_matrix_complex* MAT_i1_0__MAT_i1_2__dM = gsl_matrix_complex_alloc(dim, dim);
                matrix_multiprod(array118, 3, MAT_i1_0__MAT_i1_2__dM);
                gsl_complex trMAT_i1_0__MAT_i1_2__dM = trace(MAT_i1_0__MAT_i1_2__dM);
                gsl_matrix_complex_free(MAT_i1_0__MAT_i1_2__dM);
                free(array118);
                gsl_matrix_complex** array119 = malloc(3*sizeof(gsl_matrix_complex*));
                array119[0] = MAT[i1[1]];
                array119[1] = MAT[i1[2]];
                array119[2] = dM;
                gsl_matrix_complex* MAT_i1_1__MAT_i1_2__dM = gsl_matrix_complex_alloc(dim, dim);
                matrix_multiprod(array119, 3, MAT_i1_1__MAT_i1_2__dM);
                gsl_complex trMAT_i1_1__MAT_i1_2__dM = trace(MAT_i1_1__MAT_i1_2__dM);
                gsl_matrix_complex_free(MAT_i1_1__MAT_i1_2__dM);
                free(array119);
                gsl_matrix_complex** array120 = malloc(4*sizeof(gsl_matrix_complex*));
                array120[0] = MAT[i1[0]];
                array120[1] = MAT[i1[1]];
                array120[2] = MAT[i1[2]];
                array120[3] = dM;
                gsl_matrix_complex* MAT_i1_0__MAT_i1_1__MAT_i1_2__dM = gsl_matrix_complex_alloc(dim, dim);
                matrix_multiprod(array120, 4, MAT_i1_0__MAT_i1_1__MAT_i1_2__dM);
                gsl_complex trMAT_i1_0__MAT_i1_1__MAT_i1_2__dM = trace(MAT_i1_0__MAT_i1_1__MAT_i1_2__dM);
                gsl_matrix_complex_free(MAT_i1_0__MAT_i1_1__MAT_i1_2__dM);
                free(array120);
                gsl_matrix_complex** array121 = malloc(4*sizeof(gsl_matrix_complex*));
                array121[0] = gamma[i1[0]];
                array121[1] = gamma[uM];
                array121[2] = gamma[i1[1]];
                array121[3] = gamma[i1[2]];
                gsl_matrix_complex* gamma_i1_0__gamma_uM_gamma_i1_1__gamma_i1_2__ = gsl_matrix_complex_alloc(dimG, dimG);
                matrix_multiprod(array121, 4, gamma_i1_0__gamma_uM_gamma_i1_1__gamma_i1_2__);
                gsl_complex trgamma_i1_0__gamma_uM_gamma_i1_1__gamma_i1_2__ = trace(gamma_i1_0__gamma_uM_gamma_i1_1__gamma_i1_2__);
                gsl_matrix_complex_free(gamma_i1_0__gamma_uM_gamma_i1_1__gamma_i1_2__);
                free(array121);
                gsl_matrix_complex** array122 = malloc(4*sizeof(gsl_matrix_complex*));
                array122[0] = MAT[i1[0]];
                array122[1] = MAT[i1[2]];
                array122[2] = MAT[i1[1]];
                array122[3] = dM;
                gsl_matrix_complex* MAT_i1_0__MAT_i1_2__MAT_i1_1__dM = gsl_matrix_complex_alloc(dim, dim);
                matrix_multiprod(array122, 4, MAT_i1_0__MAT_i1_2__MAT_i1_1__dM);
                gsl_complex trMAT_i1_0__MAT_i1_2__MAT_i1_1__dM = trace(MAT_i1_0__MAT_i1_2__MAT_i1_1__dM);
                gsl_matrix_complex_free(MAT_i1_0__MAT_i1_2__MAT_i1_1__dM);
                free(array122);
                gsl_matrix_complex** array123 = malloc(4*sizeof(gsl_matrix_complex*));
                array123[0] = MAT[i1[0]];
                array123[1] = dM;
                array123[2] = MAT[i1[1]];
                array123[3] = MAT[i1[2]];
                gsl_matrix_complex* MAT_i1_0__dMMAT_i1_1__MAT_i1_2__ = gsl_matrix_complex_alloc(dim, dim);
                matrix_multiprod(array123, 4, MAT_i1_0__dMMAT_i1_1__MAT_i1_2__);
                gsl_complex trMAT_i1_0__dMMAT_i1_1__MAT_i1_2__ = trace(MAT_i1_0__dMMAT_i1_1__MAT_i1_2__);
                gsl_matrix_complex_free(MAT_i1_0__dMMAT_i1_1__MAT_i1_2__);
                free(array123);
                gsl_matrix_complex** array124 = malloc(4*sizeof(gsl_matrix_complex*));
                array124[0] = gamma[i1[0]];
                array124[1] = gamma[i1[1]];
                array124[2] = gamma[uM];
                array124[3] = gamma[i1[2]];
                gsl_matrix_complex* gamma_i1_0__gamma_i1_1__gamma_uM_gamma_i1_2__ = gsl_matrix_complex_alloc(dimG, dimG);
                matrix_multiprod(array124, 4, gamma_i1_0__gamma_i1_1__gamma_uM_gamma_i1_2__);
                gsl_complex trgamma_i1_0__gamma_i1_1__gamma_uM_gamma_i1_2__ = trace(gamma_i1_0__gamma_i1_1__gamma_uM_gamma_i1_2__);
                gsl_matrix_complex_free(gamma_i1_0__gamma_i1_1__gamma_uM_gamma_i1_2__);
                free(array124);
                gsl_matrix_complex** array125 = malloc(4*sizeof(gsl_matrix_complex*));
                array125[0] = MAT[i1[0]];
                array125[1] = MAT[i1[2]];
                array125[2] = dM;
                array125[3] = MAT[i1[1]];
                gsl_matrix_complex* MAT_i1_0__MAT_i1_2__dMMAT_i1_1__ = gsl_matrix_complex_alloc(dim, dim);
                matrix_multiprod(array125, 4, MAT_i1_0__MAT_i1_2__dMMAT_i1_1__);
                gsl_complex trMAT_i1_0__MAT_i1_2__dMMAT_i1_1__ = trace(MAT_i1_0__MAT_i1_2__dMMAT_i1_1__);
                gsl_matrix_complex_free(MAT_i1_0__MAT_i1_2__dMMAT_i1_1__);
                free(array125);
                gsl_matrix_complex** array126 = malloc(4*sizeof(gsl_matrix_complex*));
                array126[0] = MAT[i1[0]];
                array126[1] = MAT[i1[1]];
                array126[2] = dM;
                array126[3] = MAT[i1[2]];
                gsl_matrix_complex* MAT_i1_0__MAT_i1_1__dMMAT_i1_2__ = gsl_matrix_complex_alloc(dim, dim);
                matrix_multiprod(array126, 4, MAT_i1_0__MAT_i1_1__dMMAT_i1_2__);
                gsl_complex trMAT_i1_0__MAT_i1_1__dMMAT_i1_2__ = trace(MAT_i1_0__MAT_i1_1__dMMAT_i1_2__);
                gsl_matrix_complex_free(MAT_i1_0__MAT_i1_1__dMMAT_i1_2__);
                free(array126);
                jfac_d = 0.5*(1-e[i1[0]]+1-e[uM]+1-e[i1[2]]+1-e[i1[1]]);
                jfac_i = (int)jfac_d % 4;
                if(jfac_i == 0)
                    pfac = gsl_complex_rect(dim*(1*e[uM]*e[i1[0]]*e[i1[1]]*e[i1[2]]+1*e[uM]*e[i1[0]]*e[i1[1]]*e[i1[2]]), 0);
                if(jfac_i == 1)
                    pfac = gsl_complex_rect(0, dim*(1*e[uM]*e[i1[0]]*e[i1[1]]*e[i1[2]]+1*e[uM]*e[i1[0]]*e[i1[1]]*e[i1[2]]));
                if(jfac_i == 2)
                    pfac = gsl_complex_rect(-dim*(1*e[uM]*e[i1[0]]*e[i1[1]]*e[i1[2]]+1*e[uM]*e[i1[0]]*e[i1[1]]*e[i1[2]]), 0);
                if(jfac_i == 3)
                    pfac = gsl_complex_rect(0, -dim*(1*e[uM]*e[i1[0]]*e[i1[1]]*e[i1[2]]+1*e[uM]*e[i1[0]]*e[i1[1]]*e[i1[2]]));
                res = gsl_complex_add(res, gsl_complex_mul(gsl_complex_mul(trgamma_i1_0__gamma_i1_1__gamma_i1_2__gamma_uM_, trMAT_i1_0__dMMAT_i1_2__MAT_i1_1__), pfac));
                jfac_d = 0.5*(1-e[i1[0]]+1-e[i1[1]]+1-e[uM]+1-e[i1[2]]);
                jfac_i = (int)jfac_d % 4;
                if(jfac_i == 0)
                    pfac = gsl_complex_rect(1*e[uM]*e[i1[1]]*e[i1[2]]+1*e[uM]*e[i1[1]]*e[i1[2]], 0);
                if(jfac_i == 1)
                    pfac = gsl_complex_rect(0, 1*e[uM]*e[i1[1]]*e[i1[2]]+1*e[uM]*e[i1[1]]*e[i1[2]]);
                if(jfac_i == 2)
                    pfac = gsl_complex_rect(-1*e[uM]*e[i1[1]]*e[i1[2]]+1*e[uM]*e[i1[1]]*e[i1[2]], 0);
                if(jfac_i == 3)
                    pfac = gsl_complex_rect(0, -1*e[uM]*e[i1[1]]*e[i1[2]]+1*e[uM]*e[i1[1]]*e[i1[2]]);
                res = gsl_complex_add(res, gsl_complex_mul(gsl_complex_mul(gsl_complex_mul(trgamma_i1_0__gamma_i1_1__gamma_i1_2__gamma_uM_, trMAT_i1_0__), trMAT_i1_1__dMMAT_i1_2__), pfac));
                jfac_d = 0.5*(1-e[i1[0]]+1-e[uM]+1-e[i1[2]]+1-e[i1[1]]);
                jfac_i = (int)jfac_d % 4;
                if(jfac_i == 0)
                    pfac = gsl_complex_rect(1*e[uM]*e[i1[0]]*e[i1[2]]+1*e[uM]*e[i1[0]]*e[i1[2]], 0);
                if(jfac_i == 1)
                    pfac = gsl_complex_rect(0, 1*e[uM]*e[i1[0]]*e[i1[2]]+1*e[uM]*e[i1[0]]*e[i1[2]]);
                if(jfac_i == 2)
                    pfac = gsl_complex_rect(-1*e[uM]*e[i1[0]]*e[i1[2]]+1*e[uM]*e[i1[0]]*e[i1[2]], 0);
                if(jfac_i == 3)
                    pfac = gsl_complex_rect(0, -1*e[uM]*e[i1[0]]*e[i1[2]]+1*e[uM]*e[i1[0]]*e[i1[2]]);
                res = gsl_complex_add(res, gsl_complex_mul(gsl_complex_mul(gsl_complex_mul(trgamma_i1_0__gamma_i1_1__gamma_i1_2__gamma_uM_, trMAT_i1_0__dMMAT_i1_2__), trMAT_i1_1__), pfac));
                jfac_d = 0.5*(1-e[i1[0]]+1-e[i1[1]]+1-e[i1[2]]+1-e[uM]);
                jfac_i = (int)jfac_d % 4;
                if(jfac_i == 0)
                    pfac = gsl_complex_rect(1*e[uM]*e[i1[2]]+1*e[i1[0]]*e[i1[1]]+1*e[uM]*e[i1[2]]+1*e[i1[0]]*e[i1[1]], 0);
                if(jfac_i == 1)
                    pfac = gsl_complex_rect(0, 1*e[uM]*e[i1[2]]+1*e[i1[0]]*e[i1[1]]+1*e[uM]*e[i1[2]]+1*e[i1[0]]*e[i1[1]]);
                if(jfac_i == 2)
                    pfac = gsl_complex_rect(-1*e[uM]*e[i1[2]]+1*e[i1[0]]*e[i1[1]]+1*e[uM]*e[i1[2]]+1*e[i1[0]]*e[i1[1]], 0);
                if(jfac_i == 3)
                    pfac = gsl_complex_rect(0, -1*e[uM]*e[i1[2]]+1*e[i1[0]]*e[i1[1]]+1*e[uM]*e[i1[2]]+1*e[i1[0]]*e[i1[1]]);
                res = gsl_complex_add(res, gsl_complex_mul(gsl_complex_mul(gsl_complex_mul(trgamma_i1_0__gamma_i1_1__gamma_i1_2__gamma_uM_, trMAT_i1_0__MAT_i1_1__), trMAT_i1_2__dM), pfac));
                jfac_d = 0.5*(1-e[i1[0]]+1-e[uM]+1-e[i1[1]]+1-e[i1[2]]);
                jfac_i = (int)jfac_d % 4;
                if(jfac_i == 0)
                    pfac = gsl_complex_rect(1*e[uM]*e[i1[0]]*e[i1[1]]+1*e[uM]*e[i1[0]]*e[i1[1]], 0);
                if(jfac_i == 1)
                    pfac = gsl_complex_rect(0, 1*e[uM]*e[i1[0]]*e[i1[1]]+1*e[uM]*e[i1[0]]*e[i1[1]]);
                if(jfac_i == 2)
                    pfac = gsl_complex_rect(-1*e[uM]*e[i1[0]]*e[i1[1]]+1*e[uM]*e[i1[0]]*e[i1[1]], 0);
                if(jfac_i == 3)
                    pfac = gsl_complex_rect(0, -1*e[uM]*e[i1[0]]*e[i1[1]]+1*e[uM]*e[i1[0]]*e[i1[1]]);
                res = gsl_complex_add(res, gsl_complex_mul(gsl_complex_mul(gsl_complex_mul(trgamma_i1_0__gamma_i1_1__gamma_i1_2__gamma_uM_, trMAT_i1_0__dMMAT_i1_1__), trMAT_i1_2__), pfac));
                jfac_d = 0.5*(1-e[i1[0]]+1-e[i1[2]]+1-e[i1[1]]+1-e[uM]);
                jfac_i = (int)jfac_d % 4;
                if(jfac_i == 0)
                    pfac = gsl_complex_rect(1*e[uM]*e[i1[1]]+1*e[i1[0]]*e[i1[2]]+1*e[uM]*e[i1[1]]+1*e[i1[0]]*e[i1[2]], 0);
                if(jfac_i == 1)
                    pfac = gsl_complex_rect(0, 1*e[uM]*e[i1[1]]+1*e[i1[0]]*e[i1[2]]+1*e[uM]*e[i1[1]]+1*e[i1[0]]*e[i1[2]]);
                if(jfac_i == 2)
                    pfac = gsl_complex_rect(-1*e[uM]*e[i1[1]]+1*e[i1[0]]*e[i1[2]]+1*e[uM]*e[i1[1]]+1*e[i1[0]]*e[i1[2]], 0);
                if(jfac_i == 3)
                    pfac = gsl_complex_rect(0, -1*e[uM]*e[i1[1]]+1*e[i1[0]]*e[i1[2]]+1*e[uM]*e[i1[1]]+1*e[i1[0]]*e[i1[2]]);
                res = gsl_complex_add(res, gsl_complex_mul(gsl_complex_mul(gsl_complex_mul(trgamma_i1_0__gamma_i1_1__gamma_i1_2__gamma_uM_, trMAT_i1_0__MAT_i1_2__), trMAT_i1_1__dM), pfac));
                jfac_d = 0.5*(1-e[i1[0]]+1-e[uM]+1-e[i1[1]]+1-e[i1[2]]);
                jfac_i = (int)jfac_d % 4;
                if(jfac_i == 0)
                    pfac = gsl_complex_rect(1*e[uM]*e[i1[0]]+1*e[i1[1]]*e[i1[2]]+1*e[uM]*e[i1[0]]+1*e[i1[1]]*e[i1[2]], 0);
                if(jfac_i == 1)
                    pfac = gsl_complex_rect(0, 1*e[uM]*e[i1[0]]+1*e[i1[1]]*e[i1[2]]+1*e[uM]*e[i1[0]]+1*e[i1[1]]*e[i1[2]]);
                if(jfac_i == 2)
                    pfac = gsl_complex_rect(-1*e[uM]*e[i1[0]]+1*e[i1[1]]*e[i1[2]]+1*e[uM]*e[i1[0]]+1*e[i1[1]]*e[i1[2]], 0);
                if(jfac_i == 3)
                    pfac = gsl_complex_rect(0, -1*e[uM]*e[i1[0]]+1*e[i1[1]]*e[i1[2]]+1*e[uM]*e[i1[0]]+1*e[i1[1]]*e[i1[2]]);
                res = gsl_complex_add(res, gsl_complex_mul(gsl_complex_mul(gsl_complex_mul(trgamma_i1_0__gamma_i1_1__gamma_i1_2__gamma_uM_, trMAT_i1_0__dM), trMAT_i1_1__MAT_i1_2__), pfac));
                jfac_d = 0.5*(1-e[i1[0]]+1-e[i1[1]]+1-e[i1[2]]+1-e[uM]);
                jfac_i = (int)jfac_d % 4;
                if(jfac_i == 0)
                    pfac = gsl_complex_rect(1*e[uM]+1*e[uM], 0);
                if(jfac_i == 1)
                    pfac = gsl_complex_rect(0, 1*e[uM]+1*e[uM]);
                if(jfac_i == 2)
                    pfac = gsl_complex_rect(-1*e[uM]+1*e[uM], 0);
                if(jfac_i == 3)
                    pfac = gsl_complex_rect(0, -1*e[uM]+1*e[uM]);
                res = gsl_complex_add(res, gsl_complex_mul(gsl_complex_mul(gsl_complex_mul(trgamma_i1_0__gamma_i1_1__gamma_i1_2__gamma_uM_, trMAT_i1_0__MAT_i1_1__MAT_i1_2__), trdM), pfac));
                jfac_d = 0.5*(1-e[i1[0]]+1-e[i1[2]]+1-e[i1[1]]+1-e[uM]);
                jfac_i = (int)jfac_d % 4;
                if(jfac_i == 0)
                    pfac = gsl_complex_rect(1*e[i1[0]]*e[i1[1]]*e[i1[2]]+1*e[i1[0]]*e[i1[1]]*e[i1[2]], 0);
                if(jfac_i == 1)
                    pfac = gsl_complex_rect(0, 1*e[i1[0]]*e[i1[1]]*e[i1[2]]+1*e[i1[0]]*e[i1[1]]*e[i1[2]]);
                if(jfac_i == 2)
                    pfac = gsl_complex_rect(-1*e[i1[0]]*e[i1[1]]*e[i1[2]]+1*e[i1[0]]*e[i1[1]]*e[i1[2]], 0);
                if(jfac_i == 3)
                    pfac = gsl_complex_rect(0, -1*e[i1[0]]*e[i1[1]]*e[i1[2]]+1*e[i1[0]]*e[i1[1]]*e[i1[2]]);
                res = gsl_complex_add(res, gsl_complex_mul(gsl_complex_mul(gsl_complex_mul(trgamma_i1_0__gamma_i1_1__gamma_i1_2__gamma_uM_, trMAT_i1_0__MAT_i1_2__MAT_i1_1__), trdM), pfac));
                jfac_d = 0.5*(1-e[i1[0]]+1-e[i1[1]]+1-e[uM]+1-e[i1[2]]);
                jfac_i = (int)jfac_d % 4;
                if(jfac_i == 0)
                    pfac = gsl_complex_rect(1*e[i1[2]]+1*e[i1[2]], 0);
                if(jfac_i == 1)
                    pfac = gsl_complex_rect(0, 1*e[i1[2]]+1*e[i1[2]]);
                if(jfac_i == 2)
                    pfac = gsl_complex_rect(-1*e[i1[2]]+1*e[i1[2]], 0);
                if(jfac_i == 3)
                    pfac = gsl_complex_rect(0, -1*e[i1[2]]+1*e[i1[2]]);
                res = gsl_complex_add(res, gsl_complex_mul(gsl_complex_mul(gsl_complex_mul(trgamma_i1_0__gamma_i1_1__gamma_i1_2__gamma_uM_, trMAT_i1_0__MAT_i1_1__dM), trMAT_i1_2__), pfac));
                jfac_d = 0.5*(1-e[i1[0]]+1-e[i1[2]]+1-e[uM]+1-e[i1[1]]);
                jfac_i = (int)jfac_d % 4;
                if(jfac_i == 0)
                    pfac = gsl_complex_rect(1*e[i1[1]]+1*e[i1[1]], 0);
                if(jfac_i == 1)
                    pfac = gsl_complex_rect(0, 1*e[i1[1]]+1*e[i1[1]]);
                if(jfac_i == 2)
                    pfac = gsl_complex_rect(-1*e[i1[1]]+1*e[i1[1]], 0);
                if(jfac_i == 3)
                    pfac = gsl_complex_rect(0, -1*e[i1[1]]+1*e[i1[1]]);
                res = gsl_complex_add(res, gsl_complex_mul(gsl_complex_mul(gsl_complex_mul(trgamma_i1_0__gamma_i1_1__gamma_i1_2__gamma_uM_, trMAT_i1_0__MAT_i1_2__dM), trMAT_i1_1__), pfac));
                jfac_d = 0.5*(1-e[i1[0]]+1-e[i1[1]]+1-e[i1[2]]+1-e[uM]);
                jfac_i = (int)jfac_d % 4;
                if(jfac_i == 0)
                    pfac = gsl_complex_rect(1*e[i1[0]]+1*e[i1[0]], 0);
                if(jfac_i == 1)
                    pfac = gsl_complex_rect(0, 1*e[i1[0]]+1*e[i1[0]]);
                if(jfac_i == 2)
                    pfac = gsl_complex_rect(-1*e[i1[0]]+1*e[i1[0]], 0);
                if(jfac_i == 3)
                    pfac = gsl_complex_rect(0, -1*e[i1[0]]+1*e[i1[0]]);
                res = gsl_complex_add(res, gsl_complex_mul(gsl_complex_mul(gsl_complex_mul(trgamma_i1_0__gamma_i1_1__gamma_i1_2__gamma_uM_, trMAT_i1_0__), trMAT_i1_1__MAT_i1_2__dM), pfac));
                jfac_d = 0.5*(1-e[i1[0]]+1-e[i1[1]]+1-e[i1[2]]+1-e[uM]);
                jfac_i = (int)jfac_d % 4;
                if(jfac_i == 0)
                    pfac = gsl_complex_rect(dim*(1*1+1*1), 0);
                if(jfac_i == 1)
                    pfac = gsl_complex_rect(0, dim*(1*1+1*1));
                if(jfac_i == 2)
                    pfac = gsl_complex_rect(-dim*(1*1+1*1), 0);
                if(jfac_i == 3)
                    pfac = gsl_complex_rect(0, -dim*(1*1+1*1));
                res = gsl_complex_add(res, gsl_complex_mul(gsl_complex_mul(trgamma_i1_0__gamma_i1_1__gamma_i1_2__gamma_uM_, trMAT_i1_0__MAT_i1_1__MAT_i1_2__dM), pfac));
                jfac_d = 0.5*(1-e[i1[0]]+1-e[i1[2]]+1-e[i1[1]]+1-e[uM]);
                jfac_i = (int)jfac_d % 4;
                if(jfac_i == 0)
                    pfac = gsl_complex_rect(dim*(1*e[uM]*e[i1[0]]*e[i1[1]]*e[i1[2]]), 0);
                if(jfac_i == 1)
                    pfac = gsl_complex_rect(0, dim*(1*e[uM]*e[i1[0]]*e[i1[1]]*e[i1[2]]));
                if(jfac_i == 2)
                    pfac = gsl_complex_rect(-dim*(1*e[uM]*e[i1[0]]*e[i1[1]]*e[i1[2]]), 0);
                if(jfac_i == 3)
                    pfac = gsl_complex_rect(0, -dim*(1*e[uM]*e[i1[0]]*e[i1[1]]*e[i1[2]]));
                res = gsl_complex_add(res, gsl_complex_mul(gsl_complex_mul(trgamma_i1_0__gamma_uM_gamma_i1_1__gamma_i1_2__, trMAT_i1_0__MAT_i1_2__MAT_i1_1__dM), pfac));
                jfac_d = 0.5*(1-e[i1[0]]+1-e[i1[1]]+1-e[uM]+1-e[i1[2]]);
                jfac_i = (int)jfac_d % 4;
                if(jfac_i == 0)
                    pfac = gsl_complex_rect(1*e[uM]*e[i1[1]]*e[i1[2]], 0);
                if(jfac_i == 1)
                    pfac = gsl_complex_rect(0, 1*e[uM]*e[i1[1]]*e[i1[2]]);
                if(jfac_i == 2)
                    pfac = gsl_complex_rect(-1*e[uM]*e[i1[1]]*e[i1[2]], 0);
                if(jfac_i == 3)
                    pfac = gsl_complex_rect(0, -1*e[uM]*e[i1[1]]*e[i1[2]]);
                res = gsl_complex_add(res, gsl_complex_mul(gsl_complex_mul(gsl_complex_mul(trgamma_i1_0__gamma_uM_gamma_i1_1__gamma_i1_2__, trMAT_i1_0__), trMAT_i1_1__dMMAT_i1_2__), pfac));
                jfac_d = 0.5*(1-e[i1[0]]+1-e[i1[2]]+1-e[uM]+1-e[i1[1]]);
                jfac_i = (int)jfac_d % 4;
                if(jfac_i == 0)
                    pfac = gsl_complex_rect(1*e[uM]*e[i1[0]]*e[i1[2]], 0);
                if(jfac_i == 1)
                    pfac = gsl_complex_rect(0, 1*e[uM]*e[i1[0]]*e[i1[2]]);
                if(jfac_i == 2)
                    pfac = gsl_complex_rect(-1*e[uM]*e[i1[0]]*e[i1[2]], 0);
                if(jfac_i == 3)
                    pfac = gsl_complex_rect(0, -1*e[uM]*e[i1[0]]*e[i1[2]]);
                res = gsl_complex_add(res, gsl_complex_mul(gsl_complex_mul(gsl_complex_mul(trgamma_i1_0__gamma_uM_gamma_i1_1__gamma_i1_2__, trMAT_i1_0__MAT_i1_2__dM), trMAT_i1_1__), pfac));
                jfac_d = 0.5*(1-e[i1[0]]+1-e[i1[1]]+1-e[i1[2]]+1-e[uM]);
                jfac_i = (int)jfac_d % 4;
                if(jfac_i == 0)
                    pfac = gsl_complex_rect(1*e[uM]*e[i1[2]]+1*e[i1[0]]*e[i1[1]], 0);
                if(jfac_i == 1)
                    pfac = gsl_complex_rect(0, 1*e[uM]*e[i1[2]]+1*e[i1[0]]*e[i1[1]]);
                if(jfac_i == 2)
                    pfac = gsl_complex_rect(-1*e[uM]*e[i1[2]]+1*e[i1[0]]*e[i1[1]], 0);
                if(jfac_i == 3)
                    pfac = gsl_complex_rect(0, -1*e[uM]*e[i1[2]]+1*e[i1[0]]*e[i1[1]]);
                res = gsl_complex_add(res, gsl_complex_mul(gsl_complex_mul(gsl_complex_mul(trgamma_i1_0__gamma_uM_gamma_i1_1__gamma_i1_2__, trMAT_i1_0__MAT_i1_1__), trMAT_i1_2__dM), pfac));
                jfac_d = 0.5*(1-e[i1[0]]+1-e[i1[1]]+1-e[uM]+1-e[i1[2]]);
                jfac_i = (int)jfac_d % 4;
                if(jfac_i == 0)
                    pfac = gsl_complex_rect(1*e[uM]*e[i1[0]]*e[i1[1]], 0);
                if(jfac_i == 1)
                    pfac = gsl_complex_rect(0, 1*e[uM]*e[i1[0]]*e[i1[1]]);
                if(jfac_i == 2)
                    pfac = gsl_complex_rect(-1*e[uM]*e[i1[0]]*e[i1[1]], 0);
                if(jfac_i == 3)
                    pfac = gsl_complex_rect(0, -1*e[uM]*e[i1[0]]*e[i1[1]]);
                res = gsl_complex_add(res, gsl_complex_mul(gsl_complex_mul(gsl_complex_mul(trgamma_i1_0__gamma_uM_gamma_i1_1__gamma_i1_2__, trMAT_i1_0__MAT_i1_1__dM), trMAT_i1_2__), pfac));
                jfac_d = 0.5*(1-e[i1[0]]+1-e[i1[2]]+1-e[i1[1]]+1-e[uM]);
                jfac_i = (int)jfac_d % 4;
                if(jfac_i == 0)
                    pfac = gsl_complex_rect(1*e[uM]*e[i1[1]]+1*e[i1[0]]*e[i1[2]], 0);
                if(jfac_i == 1)
                    pfac = gsl_complex_rect(0, 1*e[uM]*e[i1[1]]+1*e[i1[0]]*e[i1[2]]);
                if(jfac_i == 2)
                    pfac = gsl_complex_rect(-1*e[uM]*e[i1[1]]+1*e[i1[0]]*e[i1[2]], 0);
                if(jfac_i == 3)
                    pfac = gsl_complex_rect(0, -1*e[uM]*e[i1[1]]+1*e[i1[0]]*e[i1[2]]);
                res = gsl_complex_add(res, gsl_complex_mul(gsl_complex_mul(gsl_complex_mul(trgamma_i1_0__gamma_uM_gamma_i1_1__gamma_i1_2__, trMAT_i1_0__MAT_i1_2__), trMAT_i1_1__dM), pfac));
                jfac_d = 0.5*(1-e[i1[0]]+1-e[uM]+1-e[i1[1]]+1-e[i1[2]]);
                jfac_i = (int)jfac_d % 4;
                if(jfac_i == 0)
                    pfac = gsl_complex_rect(1*e[uM]*e[i1[0]]+1*e[i1[1]]*e[i1[2]], 0);
                if(jfac_i == 1)
                    pfac = gsl_complex_rect(0, 1*e[uM]*e[i1[0]]+1*e[i1[1]]*e[i1[2]]);
                if(jfac_i == 2)
                    pfac = gsl_complex_rect(-1*e[uM]*e[i1[0]]+1*e[i1[1]]*e[i1[2]], 0);
                if(jfac_i == 3)
                    pfac = gsl_complex_rect(0, -1*e[uM]*e[i1[0]]+1*e[i1[1]]*e[i1[2]]);
                res = gsl_complex_add(res, gsl_complex_mul(gsl_complex_mul(gsl_complex_mul(trgamma_i1_0__gamma_uM_gamma_i1_1__gamma_i1_2__, trMAT_i1_0__dM), trMAT_i1_1__MAT_i1_2__), pfac));
                jfac_d = 0.5*(1-e[i1[0]]+1-e[i1[1]]+1-e[i1[2]]+1-e[uM]);
                jfac_i = (int)jfac_d % 4;
                if(jfac_i == 0)
                    pfac = gsl_complex_rect(1*e[uM], 0);
                if(jfac_i == 1)
                    pfac = gsl_complex_rect(0, 1*e[uM]);
                if(jfac_i == 2)
                    pfac = gsl_complex_rect(-1*e[uM], 0);
                if(jfac_i == 3)
                    pfac = gsl_complex_rect(0, -1*e[uM]);
                res = gsl_complex_add(res, gsl_complex_mul(gsl_complex_mul(gsl_complex_mul(trgamma_i1_0__gamma_uM_gamma_i1_1__gamma_i1_2__, trMAT_i1_0__MAT_i1_1__MAT_i1_2__), trdM), pfac));
                jfac_d = 0.5*(1-e[i1[0]]+1-e[i1[2]]+1-e[i1[1]]+1-e[uM]);
                jfac_i = (int)jfac_d % 4;
                if(jfac_i == 0)
                    pfac = gsl_complex_rect(1*e[i1[0]]*e[i1[1]]*e[i1[2]], 0);
                if(jfac_i == 1)
                    pfac = gsl_complex_rect(0, 1*e[i1[0]]*e[i1[1]]*e[i1[2]]);
                if(jfac_i == 2)
                    pfac = gsl_complex_rect(-1*e[i1[0]]*e[i1[1]]*e[i1[2]], 0);
                if(jfac_i == 3)
                    pfac = gsl_complex_rect(0, -1*e[i1[0]]*e[i1[1]]*e[i1[2]]);
                res = gsl_complex_add(res, gsl_complex_mul(gsl_complex_mul(gsl_complex_mul(trgamma_i1_0__gamma_uM_gamma_i1_1__gamma_i1_2__, trMAT_i1_0__MAT_i1_2__MAT_i1_1__), trdM), pfac));
                jfac_d = 0.5*(1-e[i1[0]]+1-e[uM]+1-e[i1[1]]+1-e[i1[2]]);
                jfac_i = (int)jfac_d % 4;
                if(jfac_i == 0)
                    pfac = gsl_complex_rect(1*e[i1[2]], 0);
                if(jfac_i == 1)
                    pfac = gsl_complex_rect(0, 1*e[i1[2]]);
                if(jfac_i == 2)
                    pfac = gsl_complex_rect(-1*e[i1[2]], 0);
                if(jfac_i == 3)
                    pfac = gsl_complex_rect(0, -1*e[i1[2]]);
                res = gsl_complex_add(res, gsl_complex_mul(gsl_complex_mul(gsl_complex_mul(trgamma_i1_0__gamma_uM_gamma_i1_1__gamma_i1_2__, trMAT_i1_0__dMMAT_i1_1__), trMAT_i1_2__), pfac));
                jfac_d = 0.5*(1-e[i1[0]]+1-e[uM]+1-e[i1[2]]+1-e[i1[1]]);
                jfac_i = (int)jfac_d % 4;
                if(jfac_i == 0)
                    pfac = gsl_complex_rect(1*e[i1[1]], 0);
                if(jfac_i == 1)
                    pfac = gsl_complex_rect(0, 1*e[i1[1]]);
                if(jfac_i == 2)
                    pfac = gsl_complex_rect(-1*e[i1[1]], 0);
                if(jfac_i == 3)
                    pfac = gsl_complex_rect(0, -1*e[i1[1]]);
                res = gsl_complex_add(res, gsl_complex_mul(gsl_complex_mul(gsl_complex_mul(trgamma_i1_0__gamma_uM_gamma_i1_1__gamma_i1_2__, trMAT_i1_0__dMMAT_i1_2__), trMAT_i1_1__), pfac));
                jfac_d = 0.5*(1-e[i1[0]]+1-e[i1[1]]+1-e[i1[2]]+1-e[uM]);
                jfac_i = (int)jfac_d % 4;
                if(jfac_i == 0)
                    pfac = gsl_complex_rect(1*e[i1[0]], 0);
                if(jfac_i == 1)
                    pfac = gsl_complex_rect(0, 1*e[i1[0]]);
                if(jfac_i == 2)
                    pfac = gsl_complex_rect(-1*e[i1[0]], 0);
                if(jfac_i == 3)
                    pfac = gsl_complex_rect(0, -1*e[i1[0]]);
                res = gsl_complex_add(res, gsl_complex_mul(gsl_complex_mul(gsl_complex_mul(trgamma_i1_0__gamma_uM_gamma_i1_1__gamma_i1_2__, trMAT_i1_0__), trMAT_i1_1__MAT_i1_2__dM), pfac));
                jfac_d = 0.5*(1-e[i1[0]]+1-e[uM]+1-e[i1[1]]+1-e[i1[2]]);
                jfac_i = (int)jfac_d % 4;
                if(jfac_i == 0)
                    pfac = gsl_complex_rect(dim*(1*1), 0);
                if(jfac_i == 1)
                    pfac = gsl_complex_rect(0, dim*(1*1));
                if(jfac_i == 2)
                    pfac = gsl_complex_rect(-dim*(1*1), 0);
                if(jfac_i == 3)
                    pfac = gsl_complex_rect(0, -dim*(1*1));
                res = gsl_complex_add(res, gsl_complex_mul(gsl_complex_mul(trgamma_i1_0__gamma_uM_gamma_i1_1__gamma_i1_2__, trMAT_i1_0__dMMAT_i1_1__MAT_i1_2__), pfac));
                jfac_d = 0.5*(1-e[i1[0]]+1-e[i1[2]]+1-e[uM]+1-e[i1[1]]);
                jfac_i = (int)jfac_d % 4;
                if(jfac_i == 0)
                    pfac = gsl_complex_rect(dim*(1*e[uM]*e[i1[0]]*e[i1[1]]*e[i1[2]]), 0);
                if(jfac_i == 1)
                    pfac = gsl_complex_rect(0, dim*(1*e[uM]*e[i1[0]]*e[i1[1]]*e[i1[2]]));
                if(jfac_i == 2)
                    pfac = gsl_complex_rect(-dim*(1*e[uM]*e[i1[0]]*e[i1[1]]*e[i1[2]]), 0);
                if(jfac_i == 3)
                    pfac = gsl_complex_rect(0, -dim*(1*e[uM]*e[i1[0]]*e[i1[1]]*e[i1[2]]));
                res = gsl_complex_add(res, gsl_complex_mul(gsl_complex_mul(trgamma_i1_0__gamma_i1_1__gamma_uM_gamma_i1_2__, trMAT_i1_0__MAT_i1_2__dMMAT_i1_1__), pfac));
                jfac_d = 0.5*(1-e[i1[0]]+1-e[i1[1]]+1-e[i1[2]]+1-e[uM]);
                jfac_i = (int)jfac_d % 4;
                if(jfac_i == 0)
                    pfac = gsl_complex_rect(1*e[uM]*e[i1[1]]*e[i1[2]], 0);
                if(jfac_i == 1)
                    pfac = gsl_complex_rect(0, 1*e[uM]*e[i1[1]]*e[i1[2]]);
                if(jfac_i == 2)
                    pfac = gsl_complex_rect(-1*e[uM]*e[i1[1]]*e[i1[2]], 0);
                if(jfac_i == 3)
                    pfac = gsl_complex_rect(0, -1*e[uM]*e[i1[1]]*e[i1[2]]);
                res = gsl_complex_add(res, gsl_complex_mul(gsl_complex_mul(gsl_complex_mul(trgamma_i1_0__gamma_i1_1__gamma_uM_gamma_i1_2__, trMAT_i1_0__), trMAT_i1_1__MAT_i1_2__dM), pfac));
                jfac_d = 0.5*(1-e[i1[0]]+1-e[i1[2]]+1-e[uM]+1-e[i1[1]]);
                jfac_i = (int)jfac_d % 4;
                if(jfac_i == 0)
                    pfac = gsl_complex_rect(1*e[uM]*e[i1[0]]*e[i1[2]], 0);
                if(jfac_i == 1)
                    pfac = gsl_complex_rect(0, 1*e[uM]*e[i1[0]]*e[i1[2]]);
                if(jfac_i == 2)
                    pfac = gsl_complex_rect(-1*e[uM]*e[i1[0]]*e[i1[2]], 0);
                if(jfac_i == 3)
                    pfac = gsl_complex_rect(0, -1*e[uM]*e[i1[0]]*e[i1[2]]);
                res = gsl_complex_add(res, gsl_complex_mul(gsl_complex_mul(gsl_complex_mul(trgamma_i1_0__gamma_i1_1__gamma_uM_gamma_i1_2__, trMAT_i1_0__MAT_i1_2__dM), trMAT_i1_1__), pfac));
                jfac_d = 0.5*(1-e[i1[0]]+1-e[i1[1]]+1-e[i1[2]]+1-e[uM]);
                jfac_i = (int)jfac_d % 4;
                if(jfac_i == 0)
                    pfac = gsl_complex_rect(1*e[uM]*e[i1[2]]+1*e[i1[0]]*e[i1[1]], 0);
                if(jfac_i == 1)
                    pfac = gsl_complex_rect(0, 1*e[uM]*e[i1[2]]+1*e[i1[0]]*e[i1[1]]);
                if(jfac_i == 2)
                    pfac = gsl_complex_rect(-1*e[uM]*e[i1[2]]+1*e[i1[0]]*e[i1[1]], 0);
                if(jfac_i == 3)
                    pfac = gsl_complex_rect(0, -1*e[uM]*e[i1[2]]+1*e[i1[0]]*e[i1[1]]);
                res = gsl_complex_add(res, gsl_complex_mul(gsl_complex_mul(gsl_complex_mul(trgamma_i1_0__gamma_i1_1__gamma_uM_gamma_i1_2__, trMAT_i1_0__MAT_i1_1__), trMAT_i1_2__dM), pfac));
                jfac_d = 0.5*(1-e[i1[0]]+1-e[uM]+1-e[i1[1]]+1-e[i1[2]]);
                jfac_i = (int)jfac_d % 4;
                if(jfac_i == 0)
                    pfac = gsl_complex_rect(1*e[uM]*e[i1[0]]*e[i1[1]], 0);
                if(jfac_i == 1)
                    pfac = gsl_complex_rect(0, 1*e[uM]*e[i1[0]]*e[i1[1]]);
                if(jfac_i == 2)
                    pfac = gsl_complex_rect(-1*e[uM]*e[i1[0]]*e[i1[1]], 0);
                if(jfac_i == 3)
                    pfac = gsl_complex_rect(0, -1*e[uM]*e[i1[0]]*e[i1[1]]);
                res = gsl_complex_add(res, gsl_complex_mul(gsl_complex_mul(gsl_complex_mul(trgamma_i1_0__gamma_i1_1__gamma_uM_gamma_i1_2__, trMAT_i1_0__dMMAT_i1_1__), trMAT_i1_2__), pfac));
                jfac_d = 0.5*(1-e[i1[0]]+1-e[i1[2]]+1-e[i1[1]]+1-e[uM]);
                jfac_i = (int)jfac_d % 4;
                if(jfac_i == 0)
                    pfac = gsl_complex_rect(1*e[uM]*e[i1[1]]+1*e[i1[0]]*e[i1[2]], 0);
                if(jfac_i == 1)
                    pfac = gsl_complex_rect(0, 1*e[uM]*e[i1[1]]+1*e[i1[0]]*e[i1[2]]);
                if(jfac_i == 2)
                    pfac = gsl_complex_rect(-1*e[uM]*e[i1[1]]+1*e[i1[0]]*e[i1[2]], 0);
                if(jfac_i == 3)
                    pfac = gsl_complex_rect(0, -1*e[uM]*e[i1[1]]+1*e[i1[0]]*e[i1[2]]);
                res = gsl_complex_add(res, gsl_complex_mul(gsl_complex_mul(gsl_complex_mul(trgamma_i1_0__gamma_i1_1__gamma_uM_gamma_i1_2__, trMAT_i1_0__MAT_i1_2__), trMAT_i1_1__dM), pfac));
                jfac_d = 0.5*(1-e[i1[0]]+1-e[uM]+1-e[i1[1]]+1-e[i1[2]]);
                jfac_i = (int)jfac_d % 4;
                if(jfac_i == 0)
                    pfac = gsl_complex_rect(1*e[uM]*e[i1[0]]+1*e[i1[1]]*e[i1[2]], 0);
                if(jfac_i == 1)
                    pfac = gsl_complex_rect(0, 1*e[uM]*e[i1[0]]+1*e[i1[1]]*e[i1[2]]);
                if(jfac_i == 2)
                    pfac = gsl_complex_rect(-1*e[uM]*e[i1[0]]+1*e[i1[1]]*e[i1[2]], 0);
                if(jfac_i == 3)
                    pfac = gsl_complex_rect(0, -1*e[uM]*e[i1[0]]+1*e[i1[1]]*e[i1[2]]);
                res = gsl_complex_add(res, gsl_complex_mul(gsl_complex_mul(gsl_complex_mul(trgamma_i1_0__gamma_i1_1__gamma_uM_gamma_i1_2__, trMAT_i1_0__dM), trMAT_i1_1__MAT_i1_2__), pfac));
                jfac_d = 0.5*(1-e[i1[0]]+1-e[i1[1]]+1-e[i1[2]]+1-e[uM]);
                jfac_i = (int)jfac_d % 4;
                if(jfac_i == 0)
                    pfac = gsl_complex_rect(1*e[uM], 0);
                if(jfac_i == 1)
                    pfac = gsl_complex_rect(0, 1*e[uM]);
                if(jfac_i == 2)
                    pfac = gsl_complex_rect(-1*e[uM], 0);
                if(jfac_i == 3)
                    pfac = gsl_complex_rect(0, -1*e[uM]);
                res = gsl_complex_add(res, gsl_complex_mul(gsl_complex_mul(gsl_complex_mul(trgamma_i1_0__gamma_i1_1__gamma_uM_gamma_i1_2__, trMAT_i1_0__MAT_i1_1__MAT_i1_2__), trdM), pfac));
                jfac_d = 0.5*(1-e[i1[0]]+1-e[i1[2]]+1-e[i1[1]]+1-e[uM]);
                jfac_i = (int)jfac_d % 4;
                if(jfac_i == 0)
                    pfac = gsl_complex_rect(1*e[i1[0]]*e[i1[1]]*e[i1[2]], 0);
                if(jfac_i == 1)
                    pfac = gsl_complex_rect(0, 1*e[i1[0]]*e[i1[1]]*e[i1[2]]);
                if(jfac_i == 2)
                    pfac = gsl_complex_rect(-1*e[i1[0]]*e[i1[1]]*e[i1[2]], 0);
                if(jfac_i == 3)
                    pfac = gsl_complex_rect(0, -1*e[i1[0]]*e[i1[1]]*e[i1[2]]);
                res = gsl_complex_add(res, gsl_complex_mul(gsl_complex_mul(gsl_complex_mul(trgamma_i1_0__gamma_i1_1__gamma_uM_gamma_i1_2__, trMAT_i1_0__MAT_i1_2__MAT_i1_1__), trdM), pfac));
                jfac_d = 0.5*(1-e[i1[0]]+1-e[i1[1]]+1-e[uM]+1-e[i1[2]]);
                jfac_i = (int)jfac_d % 4;
                if(jfac_i == 0)
                    pfac = gsl_complex_rect(1*e[i1[2]], 0);
                if(jfac_i == 1)
                    pfac = gsl_complex_rect(0, 1*e[i1[2]]);
                if(jfac_i == 2)
                    pfac = gsl_complex_rect(-1*e[i1[2]], 0);
                if(jfac_i == 3)
                    pfac = gsl_complex_rect(0, -1*e[i1[2]]);
                res = gsl_complex_add(res, gsl_complex_mul(gsl_complex_mul(gsl_complex_mul(trgamma_i1_0__gamma_i1_1__gamma_uM_gamma_i1_2__, trMAT_i1_0__MAT_i1_1__dM), trMAT_i1_2__), pfac));
                jfac_d = 0.5*(1-e[i1[0]]+1-e[uM]+1-e[i1[2]]+1-e[i1[1]]);
                jfac_i = (int)jfac_d % 4;
                if(jfac_i == 0)
                    pfac = gsl_complex_rect(1*e[i1[1]], 0);
                if(jfac_i == 1)
                    pfac = gsl_complex_rect(0, 1*e[i1[1]]);
                if(jfac_i == 2)
                    pfac = gsl_complex_rect(-1*e[i1[1]], 0);
                if(jfac_i == 3)
                    pfac = gsl_complex_rect(0, -1*e[i1[1]]);
                res = gsl_complex_add(res, gsl_complex_mul(gsl_complex_mul(gsl_complex_mul(trgamma_i1_0__gamma_i1_1__gamma_uM_gamma_i1_2__, trMAT_i1_0__dMMAT_i1_2__), trMAT_i1_1__), pfac));
                jfac_d = 0.5*(1-e[i1[0]]+1-e[i1[1]]+1-e[uM]+1-e[i1[2]]);
                jfac_i = (int)jfac_d % 4;
                if(jfac_i == 0)
                    pfac = gsl_complex_rect(1*e[i1[0]], 0);
                if(jfac_i == 1)
                    pfac = gsl_complex_rect(0, 1*e[i1[0]]);
                if(jfac_i == 2)
                    pfac = gsl_complex_rect(-1*e[i1[0]], 0);
                if(jfac_i == 3)
                    pfac = gsl_complex_rect(0, -1*e[i1[0]]);
                res = gsl_complex_add(res, gsl_complex_mul(gsl_complex_mul(gsl_complex_mul(trgamma_i1_0__gamma_i1_1__gamma_uM_gamma_i1_2__, trMAT_i1_0__), trMAT_i1_1__dMMAT_i1_2__), pfac));
                jfac_d = 0.5*(1-e[i1[0]]+1-e[i1[1]]+1-e[uM]+1-e[i1[2]]);
                jfac_i = (int)jfac_d % 4;
                if(jfac_i == 0)
                    pfac = gsl_complex_rect(dim*(1*1), 0);
                if(jfac_i == 1)
                    pfac = gsl_complex_rect(0, dim*(1*1));
                if(jfac_i == 2)
                    pfac = gsl_complex_rect(-dim*(1*1), 0);
                if(jfac_i == 3)
                    pfac = gsl_complex_rect(0, -dim*(1*1));
                res = gsl_complex_add(res, gsl_complex_mul(gsl_complex_mul(trgamma_i1_0__gamma_i1_1__gamma_uM_gamma_i1_2__, trMAT_i1_0__MAT_i1_1__dMMAT_i1_2__), pfac));
            }
        }
    }
    free(i1);



    // CASE: s=2

    int* i2 = malloc(2*sizeof(int));
    for(i2[0]=0; i2[0]<nHL; i2[0]++)
    {
        for(i2[1]=0; i2[1]<nHL; i2[1]++)
        {
            gsl_matrix_complex** array20 = malloc(4*sizeof(gsl_matrix_complex*));
            array20[0] = gamma[i2[0]];
            array20[1] = gamma[i2[1]];
            array20[2] = gamma[uM];
            array20[3] = gamma[uM];
            gsl_matrix_complex* gamma_i2_0__gamma_i2_1__gamma_uM_gamma_uM_ = gsl_matrix_complex_alloc(dimG, dimG);
            matrix_multiprod(array20, 4, gamma_i2_0__gamma_i2_1__gamma_uM_gamma_uM_);
            gsl_complex trgamma_i2_0__gamma_i2_1__gamma_uM_gamma_uM_ = trace(gamma_i2_0__gamma_i2_1__gamma_uM_gamma_uM_);
            gsl_matrix_complex_free(gamma_i2_0__gamma_i2_1__gamma_uM_gamma_uM_);
            free(array20);
            gsl_matrix_complex** array21 = malloc(4*sizeof(gsl_matrix_complex*));
            array21[0] = MAT[i2[0]];
            array21[1] = dM;
            array21[2] = dM;
            array21[3] = MAT[i2[1]];
            gsl_matrix_complex* MAT_i2_0__dMdMMAT_i2_1__ = gsl_matrix_complex_alloc(dim, dim);
            matrix_multiprod(array21, 4, MAT_i2_0__dMdMMAT_i2_1__);
            gsl_complex trMAT_i2_0__dMdMMAT_i2_1__ = trace(MAT_i2_0__dMdMMAT_i2_1__);
            gsl_matrix_complex_free(MAT_i2_0__dMdMMAT_i2_1__);
            free(array21);
            gsl_complex trMAT_i2_0__ = trace(MAT[i2[0]]);
            gsl_matrix_complex** array23 = malloc(3*sizeof(gsl_matrix_complex*));
            array23[0] = MAT[i2[1]];
            array23[1] = dM;
            array23[2] = dM;
            gsl_matrix_complex* MAT_i2_1__dMdM = gsl_matrix_complex_alloc(dim, dim);
            matrix_multiprod(array23, 3, MAT_i2_1__dMdM);
            gsl_complex trMAT_i2_1__dMdM = trace(MAT_i2_1__dMdM);
            gsl_matrix_complex_free(MAT_i2_1__dMdM);
            free(array23);
            gsl_matrix_complex** array24 = malloc(3*sizeof(gsl_matrix_complex*));
            array24[0] = MAT[i2[0]];
            array24[1] = dM;
            array24[2] = dM;
            gsl_matrix_complex* MAT_i2_0__dMdM = gsl_matrix_complex_alloc(dim, dim);
            matrix_multiprod(array24, 3, MAT_i2_0__dMdM);
            gsl_complex trMAT_i2_0__dMdM = trace(MAT_i2_0__dMdM);
            gsl_matrix_complex_free(MAT_i2_0__dMdM);
            free(array24);
            gsl_complex trMAT_i2_1__ = trace(MAT[i2[1]]);
            gsl_matrix_complex** array26 = malloc(2*sizeof(gsl_matrix_complex*));
            array26[0] = MAT[i2[0]];
            array26[1] = MAT[i2[1]];
            gsl_matrix_complex* MAT_i2_0__MAT_i2_1__ = gsl_matrix_complex_alloc(dim, dim);
            matrix_multiprod(array26, 2, MAT_i2_0__MAT_i2_1__);
            gsl_complex trMAT_i2_0__MAT_i2_1__ = trace(MAT_i2_0__MAT_i2_1__);
            gsl_matrix_complex_free(MAT_i2_0__MAT_i2_1__);
            free(array26);
            gsl_matrix_complex** array27 = malloc(2*sizeof(gsl_matrix_complex*));
            array27[0] = dM;
            array27[1] = dM;
            gsl_matrix_complex* dMdM = gsl_matrix_complex_alloc(dim, dim);
            matrix_multiprod(array27, 2, dMdM);
            gsl_complex trdMdM = trace(dMdM);
            gsl_matrix_complex_free(dMdM);
            free(array27);
            gsl_matrix_complex** array28 = malloc(3*sizeof(gsl_matrix_complex*));
            array28[0] = MAT[i2[0]];
            array28[1] = dM;
            array28[2] = MAT[i2[1]];
            gsl_matrix_complex* MAT_i2_0__dMMAT_i2_1__ = gsl_matrix_complex_alloc(dim, dim);
            matrix_multiprod(array28, 3, MAT_i2_0__dMMAT_i2_1__);
            gsl_complex trMAT_i2_0__dMMAT_i2_1__ = trace(MAT_i2_0__dMMAT_i2_1__);
            gsl_matrix_complex_free(MAT_i2_0__dMMAT_i2_1__);
            free(array28);
            gsl_complex trdM = trace(dM);
            gsl_matrix_complex** array210 = malloc(2*sizeof(gsl_matrix_complex*));
            array210[0] = MAT[i2[0]];
            array210[1] = dM;
            gsl_matrix_complex* MAT_i2_0__dM = gsl_matrix_complex_alloc(dim, dim);
            matrix_multiprod(array210, 2, MAT_i2_0__dM);
            gsl_complex trMAT_i2_0__dM = trace(MAT_i2_0__dM);
            gsl_matrix_complex_free(MAT_i2_0__dM);
            free(array210);
            gsl_matrix_complex** array211 = malloc(2*sizeof(gsl_matrix_complex*));
            array211[0] = MAT[i2[1]];
            array211[1] = dM;
            gsl_matrix_complex* MAT_i2_1__dM = gsl_matrix_complex_alloc(dim, dim);
            matrix_multiprod(array211, 2, MAT_i2_1__dM);
            gsl_complex trMAT_i2_1__dM = trace(MAT_i2_1__dM);
            gsl_matrix_complex_free(MAT_i2_1__dM);
            free(array211);
            gsl_matrix_complex** array212 = malloc(3*sizeof(gsl_matrix_complex*));
            array212[0] = MAT[i2[0]];
            array212[1] = MAT[i2[1]];
            array212[2] = dM;
            gsl_matrix_complex* MAT_i2_0__MAT_i2_1__dM = gsl_matrix_complex_alloc(dim, dim);
            matrix_multiprod(array212, 3, MAT_i2_0__MAT_i2_1__dM);
            gsl_complex trMAT_i2_0__MAT_i2_1__dM = trace(MAT_i2_0__MAT_i2_1__dM);
            gsl_matrix_complex_free(MAT_i2_0__MAT_i2_1__dM);
            free(array212);
            gsl_matrix_complex** array213 = malloc(4*sizeof(gsl_matrix_complex*));
            array213[0] = MAT[i2[0]];
            array213[1] = MAT[i2[1]];
            array213[2] = dM;
            array213[3] = dM;
            gsl_matrix_complex* MAT_i2_0__MAT_i2_1__dMdM = gsl_matrix_complex_alloc(dim, dim);
            matrix_multiprod(array213, 4, MAT_i2_0__MAT_i2_1__dMdM);
            gsl_complex trMAT_i2_0__MAT_i2_1__dMdM = trace(MAT_i2_0__MAT_i2_1__dMdM);
            gsl_matrix_complex_free(MAT_i2_0__MAT_i2_1__dMdM);
            free(array213);
            gsl_matrix_complex** array214 = malloc(4*sizeof(gsl_matrix_complex*));
            array214[0] = gamma[i2[0]];
            array214[1] = gamma[uM];
            array214[2] = gamma[i2[1]];
            array214[3] = gamma[uM];
            gsl_matrix_complex* gamma_i2_0__gamma_uM_gamma_i2_1__gamma_uM_ = gsl_matrix_complex_alloc(dimG, dimG);
            matrix_multiprod(array214, 4, gamma_i2_0__gamma_uM_gamma_i2_1__gamma_uM_);
            gsl_complex trgamma_i2_0__gamma_uM_gamma_i2_1__gamma_uM_ = trace(gamma_i2_0__gamma_uM_gamma_i2_1__gamma_uM_);
            gsl_matrix_complex_free(gamma_i2_0__gamma_uM_gamma_i2_1__gamma_uM_);
            free(array214);
            gsl_matrix_complex** array215 = malloc(4*sizeof(gsl_matrix_complex*));
            array215[0] = MAT[i2[0]];
            array215[1] = dM;
            array215[2] = MAT[i2[1]];
            array215[3] = dM;
            gsl_matrix_complex* MAT_i2_0__dMMAT_i2_1__dM = gsl_matrix_complex_alloc(dim, dim);
            matrix_multiprod(array215, 4, MAT_i2_0__dMMAT_i2_1__dM);
            gsl_complex trMAT_i2_0__dMMAT_i2_1__dM = trace(MAT_i2_0__dMMAT_i2_1__dM);
            gsl_matrix_complex_free(MAT_i2_0__dMMAT_i2_1__dM);
            free(array215);
            gsl_matrix_complex** array216 = malloc(4*sizeof(gsl_matrix_complex*));
            array216[0] = gamma[i2[0]];
            array216[1] = gamma[uM];
            array216[2] = gamma[uM];
            array216[3] = gamma[i2[1]];
            gsl_matrix_complex* gamma_i2_0__gamma_uM_gamma_uM_gamma_i2_1__ = gsl_matrix_complex_alloc(dimG, dimG);
            matrix_multiprod(array216, 4, gamma_i2_0__gamma_uM_gamma_uM_gamma_i2_1__);
            gsl_complex trgamma_i2_0__gamma_uM_gamma_uM_gamma_i2_1__ = trace(gamma_i2_0__gamma_uM_gamma_uM_gamma_i2_1__);
            gsl_matrix_complex_free(gamma_i2_0__gamma_uM_gamma_uM_gamma_i2_1__);
            free(array216);
            jfac_d = 0.5*(1-e[i2[0]]+1-e[uM]+1-e[uM]+1-e[i2[1]]);
            jfac_i = (int)jfac_d % 4;
            if(jfac_i == 0)
                pfac = gsl_complex_rect(dim*(1*e[i2[0]]*e[i2[1]]+1*e[i2[0]]*e[i2[1]]+1*e[i2[0]]*e[i2[1]]), 0);
            if(jfac_i == 1)
                pfac = gsl_complex_rect(0, dim*(1*e[i2[0]]*e[i2[1]]+1*e[i2[0]]*e[i2[1]]+1*e[i2[0]]*e[i2[1]]));
            if(jfac_i == 2)
                pfac = gsl_complex_rect(-dim*(1*e[i2[0]]*e[i2[1]]+1*e[i2[0]]*e[i2[1]]+1*e[i2[0]]*e[i2[1]]), 0);
            if(jfac_i == 3)
                pfac = gsl_complex_rect(0, -dim*(1*e[i2[0]]*e[i2[1]]+1*e[i2[0]]*e[i2[1]]+1*e[i2[0]]*e[i2[1]]));
            res = gsl_complex_add(res, gsl_complex_mul(gsl_complex_mul(trgamma_i2_0__gamma_i2_1__gamma_uM_gamma_uM_, trMAT_i2_0__dMdMMAT_i2_1__), pfac));
            jfac_d = 0.5*(1-e[i2[0]]+1-e[i2[1]]+1-e[uM]+1-e[uM]);
            jfac_i = (int)jfac_d % 4;
            if(jfac_i == 0)
                pfac = gsl_complex_rect(1*e[i2[1]]+1*e[i2[0]]+1*e[i2[1]]+1*e[i2[0]]+1*e[i2[1]]+1*e[i2[0]], 0);
            if(jfac_i == 1)
                pfac = gsl_complex_rect(0, 1*e[i2[1]]+1*e[i2[0]]+1*e[i2[1]]+1*e[i2[0]]+1*e[i2[1]]+1*e[i2[0]]);
            if(jfac_i == 2)
                pfac = gsl_complex_rect(-1*e[i2[1]]+1*e[i2[0]]+1*e[i2[1]]+1*e[i2[0]]+1*e[i2[1]]+1*e[i2[0]], 0);
            if(jfac_i == 3)
                pfac = gsl_complex_rect(0, -1*e[i2[1]]+1*e[i2[0]]+1*e[i2[1]]+1*e[i2[0]]+1*e[i2[1]]+1*e[i2[0]]);
            res = gsl_complex_add(res, gsl_complex_mul(gsl_complex_mul(gsl_complex_mul(trgamma_i2_0__gamma_i2_1__gamma_uM_gamma_uM_, trMAT_i2_0__), trMAT_i2_1__dMdM), pfac));
            jfac_d = 0.5*(1-e[i2[0]]+1-e[uM]+1-e[uM]+1-e[i2[1]]);
            jfac_i = (int)jfac_d % 4;
            if(jfac_i == 0)
                pfac = gsl_complex_rect(1*e[i2[0]]+1*e[i2[1]]+1*e[i2[0]]+1*e[i2[1]]+1*e[i2[0]]+1*e[i2[1]], 0);
            if(jfac_i == 1)
                pfac = gsl_complex_rect(0, 1*e[i2[0]]+1*e[i2[1]]+1*e[i2[0]]+1*e[i2[1]]+1*e[i2[0]]+1*e[i2[1]]);
            if(jfac_i == 2)
                pfac = gsl_complex_rect(-1*e[i2[0]]+1*e[i2[1]]+1*e[i2[0]]+1*e[i2[1]]+1*e[i2[0]]+1*e[i2[1]], 0);
            if(jfac_i == 3)
                pfac = gsl_complex_rect(0, -1*e[i2[0]]+1*e[i2[1]]+1*e[i2[0]]+1*e[i2[1]]+1*e[i2[0]]+1*e[i2[1]]);
            res = gsl_complex_add(res, gsl_complex_mul(gsl_complex_mul(gsl_complex_mul(trgamma_i2_0__gamma_i2_1__gamma_uM_gamma_uM_, trMAT_i2_0__dMdM), trMAT_i2_1__), pfac));
            jfac_d = 0.5*(1-e[i2[0]]+1-e[i2[1]]+1-e[uM]+1-e[uM]);
            jfac_i = (int)jfac_d % 4;
            if(jfac_i == 0)
                pfac = gsl_complex_rect(1*1+1*e[i2[0]]*e[i2[1]]+1*1+1*e[i2[0]]*e[i2[1]]+1*1+1*e[i2[0]]*e[i2[1]], 0);
            if(jfac_i == 1)
                pfac = gsl_complex_rect(0, 1*1+1*e[i2[0]]*e[i2[1]]+1*1+1*e[i2[0]]*e[i2[1]]+1*1+1*e[i2[0]]*e[i2[1]]);
            if(jfac_i == 2)
                pfac = gsl_complex_rect(-1*1+1*e[i2[0]]*e[i2[1]]+1*1+1*e[i2[0]]*e[i2[1]]+1*1+1*e[i2[0]]*e[i2[1]], 0);
            if(jfac_i == 3)
                pfac = gsl_complex_rect(0, -1*1+1*e[i2[0]]*e[i2[1]]+1*1+1*e[i2[0]]*e[i2[1]]+1*1+1*e[i2[0]]*e[i2[1]]);
            res = gsl_complex_add(res, gsl_complex_mul(gsl_complex_mul(gsl_complex_mul(trgamma_i2_0__gamma_i2_1__gamma_uM_gamma_uM_, trMAT_i2_0__MAT_i2_1__), trdMdM), pfac));
            jfac_d = 0.5*(1-e[i2[0]]+1-e[uM]+1-e[i2[1]]+1-e[uM]);
            jfac_i = (int)jfac_d % 4;
            if(jfac_i == 0)
                pfac = gsl_complex_rect(2*e[uM]*e[i2[0]]*e[i2[1]]+1*e[uM]*e[i2[0]]*e[i2[1]]+1*e[uM]*e[i2[0]]*e[i2[1]]+2*e[uM]*e[i2[0]]*e[i2[1]], 0);
            if(jfac_i == 1)
                pfac = gsl_complex_rect(0, 2*e[uM]*e[i2[0]]*e[i2[1]]+1*e[uM]*e[i2[0]]*e[i2[1]]+1*e[uM]*e[i2[0]]*e[i2[1]]+2*e[uM]*e[i2[0]]*e[i2[1]]);
            if(jfac_i == 2)
                pfac = gsl_complex_rect(-2*e[uM]*e[i2[0]]*e[i2[1]]+1*e[uM]*e[i2[0]]*e[i2[1]]+1*e[uM]*e[i2[0]]*e[i2[1]]+2*e[uM]*e[i2[0]]*e[i2[1]], 0);
            if(jfac_i == 3)
                pfac = gsl_complex_rect(0, -2*e[uM]*e[i2[0]]*e[i2[1]]+1*e[uM]*e[i2[0]]*e[i2[1]]+1*e[uM]*e[i2[0]]*e[i2[1]]+2*e[uM]*e[i2[0]]*e[i2[1]]);
            res = gsl_complex_add(res, gsl_complex_mul(gsl_complex_mul(gsl_complex_mul(trgamma_i2_0__gamma_i2_1__gamma_uM_gamma_uM_, trMAT_i2_0__dMMAT_i2_1__), trdM), pfac));
            jfac_d = 0.5*(1-e[i2[0]]+1-e[uM]+1-e[i2[1]]+1-e[uM]);
            jfac_i = (int)jfac_d % 4;
            if(jfac_i == 0)
                pfac = gsl_complex_rect(2*e[uM]*e[i2[1]]+2*e[uM]*e[i2[0]]+1*e[uM]*e[i2[1]]+1*e[uM]*e[i2[0]]+1*e[uM]*e[i2[1]]+1*e[uM]*e[i2[0]]+2*e[uM]*e[i2[1]]+2*e[uM]*e[i2[0]], 0);
            if(jfac_i == 1)
                pfac = gsl_complex_rect(0, 2*e[uM]*e[i2[1]]+2*e[uM]*e[i2[0]]+1*e[uM]*e[i2[1]]+1*e[uM]*e[i2[0]]+1*e[uM]*e[i2[1]]+1*e[uM]*e[i2[0]]+2*e[uM]*e[i2[1]]+2*e[uM]*e[i2[0]]);
            if(jfac_i == 2)
                pfac = gsl_complex_rect(-2*e[uM]*e[i2[1]]+2*e[uM]*e[i2[0]]+1*e[uM]*e[i2[1]]+1*e[uM]*e[i2[0]]+1*e[uM]*e[i2[1]]+1*e[uM]*e[i2[0]]+2*e[uM]*e[i2[1]]+2*e[uM]*e[i2[0]], 0);
            if(jfac_i == 3)
                pfac = gsl_complex_rect(0, -2*e[uM]*e[i2[1]]+2*e[uM]*e[i2[0]]+1*e[uM]*e[i2[1]]+1*e[uM]*e[i2[0]]+1*e[uM]*e[i2[1]]+1*e[uM]*e[i2[0]]+2*e[uM]*e[i2[1]]+2*e[uM]*e[i2[0]]);
            res = gsl_complex_add(res, gsl_complex_mul(gsl_complex_mul(gsl_complex_mul(trgamma_i2_0__gamma_i2_1__gamma_uM_gamma_uM_, trMAT_i2_0__dM), trMAT_i2_1__dM), pfac));
            jfac_d = 0.5*(1-e[i2[0]]+1-e[i2[1]]+1-e[uM]+1-e[uM]);
            jfac_i = (int)jfac_d % 4;
            if(jfac_i == 0)
                pfac = gsl_complex_rect(2*e[uM]+1*e[uM]+1*e[uM]+2*e[uM], 0);
            if(jfac_i == 1)
                pfac = gsl_complex_rect(0, 2*e[uM]+1*e[uM]+1*e[uM]+2*e[uM]);
            if(jfac_i == 2)
                pfac = gsl_complex_rect(-2*e[uM]+1*e[uM]+1*e[uM]+2*e[uM], 0);
            if(jfac_i == 3)
                pfac = gsl_complex_rect(0, -2*e[uM]+1*e[uM]+1*e[uM]+2*e[uM]);
            res = gsl_complex_add(res, gsl_complex_mul(gsl_complex_mul(gsl_complex_mul(trgamma_i2_0__gamma_i2_1__gamma_uM_gamma_uM_, trMAT_i2_0__MAT_i2_1__dM), trdM), pfac));
            jfac_d = 0.5*(1-e[i2[0]]+1-e[i2[1]]+1-e[uM]+1-e[uM]);
            jfac_i = (int)jfac_d % 4;
            if(jfac_i == 0)
                pfac = gsl_complex_rect(dim*(1*1+1*1+1*1), 0);
            if(jfac_i == 1)
                pfac = gsl_complex_rect(0, dim*(1*1+1*1+1*1));
            if(jfac_i == 2)
                pfac = gsl_complex_rect(-dim*(1*1+1*1+1*1), 0);
            if(jfac_i == 3)
                pfac = gsl_complex_rect(0, -dim*(1*1+1*1+1*1));
            res = gsl_complex_add(res, gsl_complex_mul(gsl_complex_mul(trgamma_i2_0__gamma_i2_1__gamma_uM_gamma_uM_, trMAT_i2_0__MAT_i2_1__dMdM), pfac));
            jfac_d = 0.5*(1-e[i2[0]]+1-e[uM]+1-e[i2[1]]+1-e[uM]);
            jfac_i = (int)jfac_d % 4;
            if(jfac_i == 0)
                pfac = gsl_complex_rect(dim*(1*e[i2[0]]*e[i2[1]]+1*1+1*e[i2[0]]*e[i2[1]]+1*1), 0);
            if(jfac_i == 1)
                pfac = gsl_complex_rect(0, dim*(1*e[i2[0]]*e[i2[1]]+1*1+1*e[i2[0]]*e[i2[1]]+1*1));
            if(jfac_i == 2)
                pfac = gsl_complex_rect(-dim*(1*e[i2[0]]*e[i2[1]]+1*1+1*e[i2[0]]*e[i2[1]]+1*1), 0);
            if(jfac_i == 3)
                pfac = gsl_complex_rect(0, -dim*(1*e[i2[0]]*e[i2[1]]+1*1+1*e[i2[0]]*e[i2[1]]+1*1));
            res = gsl_complex_add(res, gsl_complex_mul(gsl_complex_mul(trgamma_i2_0__gamma_uM_gamma_i2_1__gamma_uM_, trMAT_i2_0__dMMAT_i2_1__dM), pfac));
            jfac_d = 0.5*(1-e[i2[0]]+1-e[i2[1]]+1-e[uM]+1-e[uM]);
            jfac_i = (int)jfac_d % 4;
            if(jfac_i == 0)
                pfac = gsl_complex_rect(1*e[i2[1]]+1*e[i2[0]]+1*e[i2[1]]+1*e[i2[0]], 0);
            if(jfac_i == 1)
                pfac = gsl_complex_rect(0, 1*e[i2[1]]+1*e[i2[0]]+1*e[i2[1]]+1*e[i2[0]]);
            if(jfac_i == 2)
                pfac = gsl_complex_rect(-1*e[i2[1]]+1*e[i2[0]]+1*e[i2[1]]+1*e[i2[0]], 0);
            if(jfac_i == 3)
                pfac = gsl_complex_rect(0, -1*e[i2[1]]+1*e[i2[0]]+1*e[i2[1]]+1*e[i2[0]]);
            res = gsl_complex_add(res, gsl_complex_mul(gsl_complex_mul(gsl_complex_mul(trgamma_i2_0__gamma_uM_gamma_i2_1__gamma_uM_, trMAT_i2_0__), trMAT_i2_1__dMdM), pfac));
            jfac_d = 0.5*(1-e[i2[0]]+1-e[uM]+1-e[uM]+1-e[i2[1]]);
            jfac_i = (int)jfac_d % 4;
            if(jfac_i == 0)
                pfac = gsl_complex_rect(1*e[i2[0]]+1*e[i2[1]]+1*e[i2[0]]+1*e[i2[1]], 0);
            if(jfac_i == 1)
                pfac = gsl_complex_rect(0, 1*e[i2[0]]+1*e[i2[1]]+1*e[i2[0]]+1*e[i2[1]]);
            if(jfac_i == 2)
                pfac = gsl_complex_rect(-1*e[i2[0]]+1*e[i2[1]]+1*e[i2[0]]+1*e[i2[1]], 0);
            if(jfac_i == 3)
                pfac = gsl_complex_rect(0, -1*e[i2[0]]+1*e[i2[1]]+1*e[i2[0]]+1*e[i2[1]]);
            res = gsl_complex_add(res, gsl_complex_mul(gsl_complex_mul(gsl_complex_mul(trgamma_i2_0__gamma_uM_gamma_i2_1__gamma_uM_, trMAT_i2_0__dMdM), trMAT_i2_1__), pfac));
            jfac_d = 0.5*(1-e[i2[0]]+1-e[i2[1]]+1-e[uM]+1-e[uM]);
            jfac_i = (int)jfac_d % 4;
            if(jfac_i == 0)
                pfac = gsl_complex_rect(1*1+1*e[i2[0]]*e[i2[1]]+1*1+1*e[i2[0]]*e[i2[1]], 0);
            if(jfac_i == 1)
                pfac = gsl_complex_rect(0, 1*1+1*e[i2[0]]*e[i2[1]]+1*1+1*e[i2[0]]*e[i2[1]]);
            if(jfac_i == 2)
                pfac = gsl_complex_rect(-1*1+1*e[i2[0]]*e[i2[1]]+1*1+1*e[i2[0]]*e[i2[1]], 0);
            if(jfac_i == 3)
                pfac = gsl_complex_rect(0, -1*1+1*e[i2[0]]*e[i2[1]]+1*1+1*e[i2[0]]*e[i2[1]]);
            res = gsl_complex_add(res, gsl_complex_mul(gsl_complex_mul(gsl_complex_mul(trgamma_i2_0__gamma_uM_gamma_i2_1__gamma_uM_, trMAT_i2_0__MAT_i2_1__), trdMdM), pfac));
            jfac_d = 0.5*(1-e[i2[0]]+1-e[i2[1]]+1-e[uM]+1-e[uM]);
            jfac_i = (int)jfac_d % 4;
            if(jfac_i == 0)
                pfac = gsl_complex_rect(1*e[uM]*e[i2[0]]*e[i2[1]]+1*e[uM]+1*e[uM]*e[i2[0]]*e[i2[1]]+1*e[uM], 0);
            if(jfac_i == 1)
                pfac = gsl_complex_rect(0, 1*e[uM]*e[i2[0]]*e[i2[1]]+1*e[uM]+1*e[uM]*e[i2[0]]*e[i2[1]]+1*e[uM]);
            if(jfac_i == 2)
                pfac = gsl_complex_rect(-1*e[uM]*e[i2[0]]*e[i2[1]]+1*e[uM]+1*e[uM]*e[i2[0]]*e[i2[1]]+1*e[uM], 0);
            if(jfac_i == 3)
                pfac = gsl_complex_rect(0, -1*e[uM]*e[i2[0]]*e[i2[1]]+1*e[uM]+1*e[uM]*e[i2[0]]*e[i2[1]]+1*e[uM]);
            res = gsl_complex_add(res, gsl_complex_mul(gsl_complex_mul(gsl_complex_mul(trgamma_i2_0__gamma_uM_gamma_i2_1__gamma_uM_, trMAT_i2_0__MAT_i2_1__dM), trdM), pfac));
            jfac_d = 0.5*(1-e[i2[0]]+1-e[uM]+1-e[i2[1]]+1-e[uM]);
            jfac_i = (int)jfac_d % 4;
            if(jfac_i == 0)
                pfac = gsl_complex_rect(1*e[uM]*e[i2[1]]+1*e[uM]*e[i2[0]]+1*e[uM]*e[i2[1]]+1*e[uM]*e[i2[0]]+1*e[uM]*e[i2[1]]+1*e[uM]*e[i2[0]]+1*e[uM]*e[i2[1]]+1*e[uM]*e[i2[0]], 0);
            if(jfac_i == 1)
                pfac = gsl_complex_rect(0, 1*e[uM]*e[i2[1]]+1*e[uM]*e[i2[0]]+1*e[uM]*e[i2[1]]+1*e[uM]*e[i2[0]]+1*e[uM]*e[i2[1]]+1*e[uM]*e[i2[0]]+1*e[uM]*e[i2[1]]+1*e[uM]*e[i2[0]]);
            if(jfac_i == 2)
                pfac = gsl_complex_rect(-1*e[uM]*e[i2[1]]+1*e[uM]*e[i2[0]]+1*e[uM]*e[i2[1]]+1*e[uM]*e[i2[0]]+1*e[uM]*e[i2[1]]+1*e[uM]*e[i2[0]]+1*e[uM]*e[i2[1]]+1*e[uM]*e[i2[0]], 0);
            if(jfac_i == 3)
                pfac = gsl_complex_rect(0, -1*e[uM]*e[i2[1]]+1*e[uM]*e[i2[0]]+1*e[uM]*e[i2[1]]+1*e[uM]*e[i2[0]]+1*e[uM]*e[i2[1]]+1*e[uM]*e[i2[0]]+1*e[uM]*e[i2[1]]+1*e[uM]*e[i2[0]]);
            res = gsl_complex_add(res, gsl_complex_mul(gsl_complex_mul(gsl_complex_mul(trgamma_i2_0__gamma_uM_gamma_i2_1__gamma_uM_, trMAT_i2_0__dM), trMAT_i2_1__dM), pfac));
            jfac_d = 0.5*(1-e[i2[0]]+1-e[uM]+1-e[i2[1]]+1-e[uM]);
            jfac_i = (int)jfac_d % 4;
            if(jfac_i == 0)
                pfac = gsl_complex_rect(1*e[uM]*e[i2[0]]*e[i2[1]]+1*e[uM]+1*e[uM]*e[i2[0]]*e[i2[1]]+1*e[uM], 0);
            if(jfac_i == 1)
                pfac = gsl_complex_rect(0, 1*e[uM]*e[i2[0]]*e[i2[1]]+1*e[uM]+1*e[uM]*e[i2[0]]*e[i2[1]]+1*e[uM]);
            if(jfac_i == 2)
                pfac = gsl_complex_rect(-1*e[uM]*e[i2[0]]*e[i2[1]]+1*e[uM]+1*e[uM]*e[i2[0]]*e[i2[1]]+1*e[uM], 0);
            if(jfac_i == 3)
                pfac = gsl_complex_rect(0, -1*e[uM]*e[i2[0]]*e[i2[1]]+1*e[uM]+1*e[uM]*e[i2[0]]*e[i2[1]]+1*e[uM]);
            res = gsl_complex_add(res, gsl_complex_mul(gsl_complex_mul(gsl_complex_mul(trgamma_i2_0__gamma_uM_gamma_i2_1__gamma_uM_, trMAT_i2_0__dMMAT_i2_1__), trdM), pfac));
            jfac_d = 0.5*(1-e[i2[0]]+1-e[i2[1]]+1-e[uM]+1-e[uM]);
            jfac_i = (int)jfac_d % 4;
            if(jfac_i == 0)
                pfac = gsl_complex_rect(dim*(1*e[i2[0]]*e[i2[1]]), 0);
            if(jfac_i == 1)
                pfac = gsl_complex_rect(0, dim*(1*e[i2[0]]*e[i2[1]]));
            if(jfac_i == 2)
                pfac = gsl_complex_rect(-dim*(1*e[i2[0]]*e[i2[1]]), 0);
            if(jfac_i == 3)
                pfac = gsl_complex_rect(0, -dim*(1*e[i2[0]]*e[i2[1]]));
            res = gsl_complex_add(res, gsl_complex_mul(gsl_complex_mul(trgamma_i2_0__gamma_uM_gamma_uM_gamma_i2_1__, trMAT_i2_0__MAT_i2_1__dMdM), pfac));
            jfac_d = 0.5*(1-e[i2[0]]+1-e[i2[1]]+1-e[uM]+1-e[uM]);
            jfac_i = (int)jfac_d % 4;
            if(jfac_i == 0)
                pfac = gsl_complex_rect(1*e[i2[1]]+1*e[i2[0]], 0);
            if(jfac_i == 1)
                pfac = gsl_complex_rect(0, 1*e[i2[1]]+1*e[i2[0]]);
            if(jfac_i == 2)
                pfac = gsl_complex_rect(-1*e[i2[1]]+1*e[i2[0]], 0);
            if(jfac_i == 3)
                pfac = gsl_complex_rect(0, -1*e[i2[1]]+1*e[i2[0]]);
            res = gsl_complex_add(res, gsl_complex_mul(gsl_complex_mul(gsl_complex_mul(trgamma_i2_0__gamma_uM_gamma_uM_gamma_i2_1__, trMAT_i2_0__), trMAT_i2_1__dMdM), pfac));
            jfac_d = 0.5*(1-e[i2[0]]+1-e[uM]+1-e[uM]+1-e[i2[1]]);
            jfac_i = (int)jfac_d % 4;
            if(jfac_i == 0)
                pfac = gsl_complex_rect(1*e[i2[0]]+1*e[i2[1]], 0);
            if(jfac_i == 1)
                pfac = gsl_complex_rect(0, 1*e[i2[0]]+1*e[i2[1]]);
            if(jfac_i == 2)
                pfac = gsl_complex_rect(-1*e[i2[0]]+1*e[i2[1]], 0);
            if(jfac_i == 3)
                pfac = gsl_complex_rect(0, -1*e[i2[0]]+1*e[i2[1]]);
            res = gsl_complex_add(res, gsl_complex_mul(gsl_complex_mul(gsl_complex_mul(trgamma_i2_0__gamma_uM_gamma_uM_gamma_i2_1__, trMAT_i2_0__dMdM), trMAT_i2_1__), pfac));
            jfac_d = 0.5*(1-e[i2[0]]+1-e[i2[1]]+1-e[uM]+1-e[uM]);
            jfac_i = (int)jfac_d % 4;
            if(jfac_i == 0)
                pfac = gsl_complex_rect(1*1+1*e[i2[0]]*e[i2[1]], 0);
            if(jfac_i == 1)
                pfac = gsl_complex_rect(0, 1*1+1*e[i2[0]]*e[i2[1]]);
            if(jfac_i == 2)
                pfac = gsl_complex_rect(-1*1+1*e[i2[0]]*e[i2[1]], 0);
            if(jfac_i == 3)
                pfac = gsl_complex_rect(0, -1*1+1*e[i2[0]]*e[i2[1]]);
            res = gsl_complex_add(res, gsl_complex_mul(gsl_complex_mul(gsl_complex_mul(trgamma_i2_0__gamma_uM_gamma_uM_gamma_i2_1__, trMAT_i2_0__MAT_i2_1__), trdMdM), pfac));
            jfac_d = 0.5*(1-e[i2[0]]+1-e[i2[1]]+1-e[uM]+1-e[uM]);
            jfac_i = (int)jfac_d % 4;
            if(jfac_i == 0)
                pfac = gsl_complex_rect(2*e[uM]*e[i2[0]]*e[i2[1]], 0);
            if(jfac_i == 1)
                pfac = gsl_complex_rect(0, 2*e[uM]*e[i2[0]]*e[i2[1]]);
            if(jfac_i == 2)
                pfac = gsl_complex_rect(-2*e[uM]*e[i2[0]]*e[i2[1]], 0);
            if(jfac_i == 3)
                pfac = gsl_complex_rect(0, -2*e[uM]*e[i2[0]]*e[i2[1]]);
            res = gsl_complex_add(res, gsl_complex_mul(gsl_complex_mul(gsl_complex_mul(trgamma_i2_0__gamma_uM_gamma_uM_gamma_i2_1__, trMAT_i2_0__MAT_i2_1__dM), trdM), pfac));
            jfac_d = 0.5*(1-e[i2[0]]+1-e[uM]+1-e[i2[1]]+1-e[uM]);
            jfac_i = (int)jfac_d % 4;
            if(jfac_i == 0)
                pfac = gsl_complex_rect(2*e[uM]*e[i2[1]]+2*e[uM]*e[i2[0]], 0);
            if(jfac_i == 1)
                pfac = gsl_complex_rect(0, 2*e[uM]*e[i2[1]]+2*e[uM]*e[i2[0]]);
            if(jfac_i == 2)
                pfac = gsl_complex_rect(-2*e[uM]*e[i2[1]]+2*e[uM]*e[i2[0]], 0);
            if(jfac_i == 3)
                pfac = gsl_complex_rect(0, -2*e[uM]*e[i2[1]]+2*e[uM]*e[i2[0]]);
            res = gsl_complex_add(res, gsl_complex_mul(gsl_complex_mul(gsl_complex_mul(trgamma_i2_0__gamma_uM_gamma_uM_gamma_i2_1__, trMAT_i2_0__dM), trMAT_i2_1__dM), pfac));
            jfac_d = 0.5*(1-e[i2[0]]+1-e[uM]+1-e[i2[1]]+1-e[uM]);
            jfac_i = (int)jfac_d % 4;
            if(jfac_i == 0)
                pfac = gsl_complex_rect(2*e[uM], 0);
            if(jfac_i == 1)
                pfac = gsl_complex_rect(0, 2*e[uM]);
            if(jfac_i == 2)
                pfac = gsl_complex_rect(-2*e[uM], 0);
            if(jfac_i == 3)
                pfac = gsl_complex_rect(0, -2*e[uM]);
            res = gsl_complex_add(res, gsl_complex_mul(gsl_complex_mul(gsl_complex_mul(trgamma_i2_0__gamma_uM_gamma_uM_gamma_i2_1__, trMAT_i2_0__dMMAT_i2_1__), trdM), pfac));
            jfac_d = 0.5*(1-e[i2[0]]+1-e[uM]+1-e[uM]+1-e[i2[1]]);
            jfac_i = (int)jfac_d % 4;
            if(jfac_i == 0)
                pfac = gsl_complex_rect(dim*(1*1), 0);
            if(jfac_i == 1)
                pfac = gsl_complex_rect(0, dim*(1*1));
            if(jfac_i == 2)
                pfac = gsl_complex_rect(-dim*(1*1), 0);
            if(jfac_i == 3)
                pfac = gsl_complex_rect(0, -dim*(1*1));
            res = gsl_complex_add(res, gsl_complex_mul(gsl_complex_mul(trgamma_i2_0__gamma_uM_gamma_uM_gamma_i2_1__, trMAT_i2_0__dMdMMAT_i2_1__), pfac));
        }
    }
    free(i2);



    // CASE: s=3

    int* i3 = malloc(1*sizeof(int));
    for(i3[0]=0; i3[0]<nHL; i3[0]++)
    {
        gsl_matrix_complex** array30 = malloc(4*sizeof(gsl_matrix_complex*));
        array30[0] = gamma[i3[0]];
        array30[1] = gamma[uM];
        array30[2] = gamma[uM];
        array30[3] = gamma[uM];
        gsl_matrix_complex* gamma_i3_0__gamma_uM_gamma_uM_gamma_uM_ = gsl_matrix_complex_alloc(dimG, dimG);
        matrix_multiprod(array30, 4, gamma_i3_0__gamma_uM_gamma_uM_gamma_uM_);
        gsl_complex trgamma_i3_0__gamma_uM_gamma_uM_gamma_uM_ = trace(gamma_i3_0__gamma_uM_gamma_uM_gamma_uM_);
        gsl_matrix_complex_free(gamma_i3_0__gamma_uM_gamma_uM_gamma_uM_);
        free(array30);
        gsl_matrix_complex** array31 = malloc(4*sizeof(gsl_matrix_complex*));
        array31[0] = MAT[i3[0]];
        array31[1] = dM;
        array31[2] = dM;
        array31[3] = dM;
        gsl_matrix_complex* MAT_i3_0__dMdMdM = gsl_matrix_complex_alloc(dim, dim);
        matrix_multiprod(array31, 4, MAT_i3_0__dMdMdM);
        gsl_complex trMAT_i3_0__dMdMdM = trace(MAT_i3_0__dMdMdM);
        gsl_matrix_complex_free(MAT_i3_0__dMdMdM);
        free(array31);
        gsl_complex trMAT_i3_0__ = trace(MAT[i3[0]]);
        gsl_matrix_complex** array33 = malloc(3*sizeof(gsl_matrix_complex*));
        array33[0] = dM;
        array33[1] = dM;
        array33[2] = dM;
        gsl_matrix_complex* dMdMdM = gsl_matrix_complex_alloc(dim, dim);
        matrix_multiprod(array33, 3, dMdMdM);
        gsl_complex trdMdMdM = trace(dMdMdM);
        gsl_matrix_complex_free(dMdMdM);
        free(array33);
        gsl_matrix_complex** array34 = malloc(3*sizeof(gsl_matrix_complex*));
        array34[0] = MAT[i3[0]];
        array34[1] = dM;
        array34[2] = dM;
        gsl_matrix_complex* MAT_i3_0__dMdM = gsl_matrix_complex_alloc(dim, dim);
        matrix_multiprod(array34, 3, MAT_i3_0__dMdM);
        gsl_complex trMAT_i3_0__dMdM = trace(MAT_i3_0__dMdM);
        gsl_matrix_complex_free(MAT_i3_0__dMdM);
        free(array34);
        gsl_complex trdM = trace(dM);
        gsl_matrix_complex** array36 = malloc(2*sizeof(gsl_matrix_complex*));
        array36[0] = MAT[i3[0]];
        array36[1] = dM;
        gsl_matrix_complex* MAT_i3_0__dM = gsl_matrix_complex_alloc(dim, dim);
        matrix_multiprod(array36, 2, MAT_i3_0__dM);
        gsl_complex trMAT_i3_0__dM = trace(MAT_i3_0__dM);
        gsl_matrix_complex_free(MAT_i3_0__dM);
        free(array36);
        gsl_matrix_complex** array37 = malloc(2*sizeof(gsl_matrix_complex*));
        array37[0] = dM;
        array37[1] = dM;
        gsl_matrix_complex* dMdM = gsl_matrix_complex_alloc(dim, dim);
        matrix_multiprod(array37, 2, dMdM);
        gsl_complex trdMdM = trace(dMdM);
        gsl_matrix_complex_free(dMdM);
        free(array37);
        jfac_d = 0.5*(1-e[i3[0]]+1-e[uM]+1-e[uM]+1-e[uM]);
        jfac_i = (int)jfac_d % 4;
        if(jfac_i == 0)
            pfac = gsl_complex_rect(dim*(1*e[uM]*e[i3[0]]+1*1+1*e[uM]*e[i3[0]]+1*1+1*e[uM]*e[i3[0]]+1*1+1*e[uM]*e[i3[0]]+1*1), 0);
        if(jfac_i == 1)
            pfac = gsl_complex_rect(0, dim*(1*e[uM]*e[i3[0]]+1*1+1*e[uM]*e[i3[0]]+1*1+1*e[uM]*e[i3[0]]+1*1+1*e[uM]*e[i3[0]]+1*1));
        if(jfac_i == 2)
            pfac = gsl_complex_rect(-dim*(1*e[uM]*e[i3[0]]+1*1+1*e[uM]*e[i3[0]]+1*1+1*e[uM]*e[i3[0]]+1*1+1*e[uM]*e[i3[0]]+1*1), 0);
        if(jfac_i == 3)
            pfac = gsl_complex_rect(0, -dim*(1*e[uM]*e[i3[0]]+1*1+1*e[uM]*e[i3[0]]+1*1+1*e[uM]*e[i3[0]]+1*1+1*e[uM]*e[i3[0]]+1*1));
        res = gsl_complex_add(res, gsl_complex_mul(gsl_complex_mul(trgamma_i3_0__gamma_uM_gamma_uM_gamma_uM_, trMAT_i3_0__dMdMdM), pfac));
        jfac_d = 0.5*(1-e[i3[0]]+1-e[uM]+1-e[uM]+1-e[uM]);
        jfac_i = (int)jfac_d % 4;
        if(jfac_i == 0)
            pfac = gsl_complex_rect(1*e[uM]+1*e[i3[0]]+1*e[uM]+1*e[i3[0]]+1*e[uM]+1*e[i3[0]]+1*e[uM]+1*e[i3[0]], 0);
        if(jfac_i == 1)
            pfac = gsl_complex_rect(0, 1*e[uM]+1*e[i3[0]]+1*e[uM]+1*e[i3[0]]+1*e[uM]+1*e[i3[0]]+1*e[uM]+1*e[i3[0]]);
        if(jfac_i == 2)
            pfac = gsl_complex_rect(-1*e[uM]+1*e[i3[0]]+1*e[uM]+1*e[i3[0]]+1*e[uM]+1*e[i3[0]]+1*e[uM]+1*e[i3[0]], 0);
        if(jfac_i == 3)
            pfac = gsl_complex_rect(0, -1*e[uM]+1*e[i3[0]]+1*e[uM]+1*e[i3[0]]+1*e[uM]+1*e[i3[0]]+1*e[uM]+1*e[i3[0]]);
        res = gsl_complex_add(res, gsl_complex_mul(gsl_complex_mul(gsl_complex_mul(trgamma_i3_0__gamma_uM_gamma_uM_gamma_uM_, trMAT_i3_0__), trdMdMdM), pfac));
        jfac_d = 0.5*(1-e[i3[0]]+1-e[uM]+1-e[uM]+1-e[uM]);
        jfac_i = (int)jfac_d % 4;
        if(jfac_i == 0)
            pfac = gsl_complex_rect(3*e[i3[0]]+3*e[uM]+2*e[i3[0]]+1*e[uM]+1*e[i3[0]]+2*e[uM]+1*e[i3[0]]+2*e[i3[0]]+2*e[uM]+1*e[uM]+3*e[i3[0]]+3*e[uM], 0);
        if(jfac_i == 1)
            pfac = gsl_complex_rect(0, 3*e[i3[0]]+3*e[uM]+2*e[i3[0]]+1*e[uM]+1*e[i3[0]]+2*e[uM]+1*e[i3[0]]+2*e[i3[0]]+2*e[uM]+1*e[uM]+3*e[i3[0]]+3*e[uM]);
        if(jfac_i == 2)
            pfac = gsl_complex_rect(-3*e[i3[0]]+3*e[uM]+2*e[i3[0]]+1*e[uM]+1*e[i3[0]]+2*e[uM]+1*e[i3[0]]+2*e[i3[0]]+2*e[uM]+1*e[uM]+3*e[i3[0]]+3*e[uM], 0);
        if(jfac_i == 3)
            pfac = gsl_complex_rect(0, -3*e[i3[0]]+3*e[uM]+2*e[i3[0]]+1*e[uM]+1*e[i3[0]]+2*e[uM]+1*e[i3[0]]+2*e[i3[0]]+2*e[uM]+1*e[uM]+3*e[i3[0]]+3*e[uM]);
        res = gsl_complex_add(res, gsl_complex_mul(gsl_complex_mul(gsl_complex_mul(trgamma_i3_0__gamma_uM_gamma_uM_gamma_uM_, trMAT_i3_0__dMdM), trdM), pfac));
        jfac_d = 0.5*(1-e[i3[0]]+1-e[uM]+1-e[uM]+1-e[uM]);
        jfac_i = (int)jfac_d % 4;
        if(jfac_i == 0)
            pfac = gsl_complex_rect(3*1+3*e[uM]*e[i3[0]]+2*1+1*e[uM]*e[i3[0]]+1*1+2*e[uM]*e[i3[0]]+1*1+2*1+2*e[uM]*e[i3[0]]+1*e[uM]*e[i3[0]]+3*1+3*e[uM]*e[i3[0]], 0);
        if(jfac_i == 1)
            pfac = gsl_complex_rect(0, 3*1+3*e[uM]*e[i3[0]]+2*1+1*e[uM]*e[i3[0]]+1*1+2*e[uM]*e[i3[0]]+1*1+2*1+2*e[uM]*e[i3[0]]+1*e[uM]*e[i3[0]]+3*1+3*e[uM]*e[i3[0]]);
        if(jfac_i == 2)
            pfac = gsl_complex_rect(-3*1+3*e[uM]*e[i3[0]]+2*1+1*e[uM]*e[i3[0]]+1*1+2*e[uM]*e[i3[0]]+1*1+2*1+2*e[uM]*e[i3[0]]+1*e[uM]*e[i3[0]]+3*1+3*e[uM]*e[i3[0]], 0);
        if(jfac_i == 3)
            pfac = gsl_complex_rect(0, -3*1+3*e[uM]*e[i3[0]]+2*1+1*e[uM]*e[i3[0]]+1*1+2*e[uM]*e[i3[0]]+1*1+2*1+2*e[uM]*e[i3[0]]+1*e[uM]*e[i3[0]]+3*1+3*e[uM]*e[i3[0]]);
        res = gsl_complex_add(res, gsl_complex_mul(gsl_complex_mul(gsl_complex_mul(trgamma_i3_0__gamma_uM_gamma_uM_gamma_uM_, trMAT_i3_0__dM), trdMdM), pfac));
    }
    free(i3);



    // CASE: s=4

    gsl_matrix_complex** array40 = malloc(4*sizeof(gsl_matrix_complex*));
    array40[0] = gamma[uM];
    array40[1] = gamma[uM];
    array40[2] = gamma[uM];
    array40[3] = gamma[uM];
    gsl_matrix_complex* gamma_uM_gamma_uM_gamma_uM_gamma_uM_ = gsl_matrix_complex_alloc(dimG, dimG);
    matrix_multiprod(array40, 4, gamma_uM_gamma_uM_gamma_uM_gamma_uM_);
    gsl_complex trgamma_uM_gamma_uM_gamma_uM_gamma_uM_ = trace(gamma_uM_gamma_uM_gamma_uM_gamma_uM_);
    gsl_matrix_complex_free(gamma_uM_gamma_uM_gamma_uM_gamma_uM_);
    free(array40);
    gsl_matrix_complex** array41 = malloc(4*sizeof(gsl_matrix_complex*));
    array41[0] = dM;
    array41[1] = dM;
    array41[2] = dM;
    array41[3] = dM;
    gsl_matrix_complex* dMdMdMdM = gsl_matrix_complex_alloc(dim, dim);
    matrix_multiprod(array41, 4, dMdMdMdM);
    gsl_complex trdMdMdMdM = trace(dMdMdMdM);
    gsl_matrix_complex_free(dMdMdMdM);
    free(array41);
    gsl_complex trdM = trace(dM);
    gsl_matrix_complex** array43 = malloc(3*sizeof(gsl_matrix_complex*));
    array43[0] = dM;
    array43[1] = dM;
    array43[2] = dM;
    gsl_matrix_complex* dMdMdM = gsl_matrix_complex_alloc(dim, dim);
    matrix_multiprod(array43, 3, dMdMdM);
    gsl_complex trdMdMdM = trace(dMdMdM);
    gsl_matrix_complex_free(dMdMdM);
    free(array43);
    gsl_matrix_complex** array44 = malloc(2*sizeof(gsl_matrix_complex*));
    array44[0] = dM;
    array44[1] = dM;
    gsl_matrix_complex* dMdM = gsl_matrix_complex_alloc(dim, dim);
    matrix_multiprod(array44, 2, dMdM);
    gsl_complex trdMdM = trace(dMdM);
    gsl_matrix_complex_free(dMdM);
    free(array44);
    jfac_d = 0.5*(1-e[uM]+1-e[uM]+1-e[uM]+1-e[uM]);
    jfac_i = (int)jfac_d % 4;
    if(jfac_i == 0)
        pfac = gsl_complex_rect(dim*(1*1+1*1), 0);
    if(jfac_i == 1)
        pfac = gsl_complex_rect(0, dim*(1*1+1*1));
    if(jfac_i == 2)
        pfac = gsl_complex_rect(-dim*(1*1+1*1), 0);
    if(jfac_i == 3)
        pfac = gsl_complex_rect(0, -dim*(1*1+1*1));
    res = gsl_complex_add(res, gsl_complex_mul(gsl_complex_mul(trgamma_uM_gamma_uM_gamma_uM_gamma_uM_, trdMdMdMdM), pfac));
    jfac_d = 0.5*(1-e[uM]+1-e[uM]+1-e[uM]+1-e[uM]);
    jfac_i = (int)jfac_d % 4;
    if(jfac_i == 0)
        pfac = gsl_complex_rect(4*e[uM]+4*e[uM], 0);
    if(jfac_i == 1)
        pfac = gsl_complex_rect(0, 4*e[uM]+4*e[uM]);
    if(jfac_i == 2)
        pfac = gsl_complex_rect(-4*e[uM]+4*e[uM], 0);
    if(jfac_i == 3)
        pfac = gsl_complex_rect(0, -4*e[uM]+4*e[uM]);
    res = gsl_complex_add(res, gsl_complex_mul(gsl_complex_mul(gsl_complex_mul(trgamma_uM_gamma_uM_gamma_uM_gamma_uM_, trdM), trdMdMdM), pfac));
    jfac_d = 0.5*(1-e[uM]+1-e[uM]+1-e[uM]+1-e[uM]);
    jfac_i = (int)jfac_d % 4;
    if(jfac_i == 0)
        pfac = gsl_complex_rect(6*1, 0);
    if(jfac_i == 1)
        pfac = gsl_complex_rect(0, 6*1);
    if(jfac_i == 2)
        pfac = gsl_complex_rect(-6*1, 0);
    if(jfac_i == 3)
        pfac = gsl_complex_rect(0, -6*1);
    res = gsl_complex_add(res, gsl_complex_mul(gsl_complex_mul(gsl_complex_mul(trgamma_uM_gamma_uM_gamma_uM_gamma_uM_, trdMdM), trdMdM), pfac));



	printf("%.20lf\n", GSL_IMAG(res));
    return GSL_REAL(res);
}

